// Playbook static content — the indicator/index catalog, plain-English indicator
// explanations, and the built-in macro calendar. Pure data (no logic, no React,
// no DOM). Dual-mode: browser global `window.PBContent` + CommonJS for Node tests.
// Loaded before app.js; app.js binds each value via `const X = PBContent.X`.
(function (root, factory) {
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.PBContent = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {

const RIBBON_CATALOG = [
  { key: 'US:^SPX',    ticker: '^SPX',    market: 'US', label: 'S&P 500',         short: 'S&P',  decimals: 0, invertColor: false },
  { key: 'US:^VIX',    ticker: '^VIX',    market: 'US', label: 'VIX',             short: 'VIX',  decimals: 2, invertColor: true  },
  { key: 'US:^DJI',    ticker: '^DJI',    market: 'US', label: 'Dow Jones',       short: 'DOW',  decimals: 0, invertColor: false },
  { key: 'US:^IXIC',   ticker: '^IXIC',   market: 'US', label: 'Nasdaq',          short: 'NDQ',  decimals: 0, invertColor: false },
  { key: 'US:^FTSE',   ticker: '^FTSE',   market: 'US', label: 'FTSE 100',        short: 'FTSE', decimals: 0, invertColor: false },
  { key: 'US:^N225',   ticker: '^N225',   market: 'US', label: 'Nikkei 225',      short: 'N225', decimals: 0, invertColor: false },
  { key: 'US:^GDAXI',  ticker: '^GDAXI',  market: 'US', label: 'DAX',             short: 'DAX',  decimals: 0, invertColor: false },
  { key: 'US:GC=F',    ticker: 'GC=F',    market: 'US', label: 'Gold',            short: 'GOLD', decimals: 2, invertColor: false },
  { key: 'US:SI=F',    ticker: 'SI=F',    market: 'US', label: 'Silver',          short: 'SLVR', decimals: 2, invertColor: false },
  { key: 'US:CL=F',    ticker: 'CL=F',    market: 'US', label: 'Crude Oil (WTI)', short: 'OIL',  decimals: 2, invertColor: false },
  { key: 'US:BZ=F',    ticker: 'BZ=F',    market: 'US', label: 'Brent Crude',     short: 'BRNT', decimals: 2, invertColor: false },
  { key: 'US:NG=F',    ticker: 'NG=F',    market: 'US', label: 'Natural Gas',     short: 'NGAS', decimals: 3, invertColor: false },
  { key: 'US:HG=F',    ticker: 'HG=F',    market: 'US', label: 'Copper',          short: 'CPPR', decimals: 3, invertColor: false },
  { key: 'US:PL=F',    ticker: 'PL=F',    market: 'US', label: 'Platinum',        short: 'PLAT', decimals: 2, invertColor: false },
  { key: 'US:BTC-USD', ticker: 'BTC-USD', market: 'US', label: 'Bitcoin',         short: 'BTC',  decimals: 0, invertColor: false },
  { key: 'US:ETH-USD', ticker: 'ETH-USD', market: 'US', label: 'Ethereum',        short: 'ETH',  decimals: 0, invertColor: false },
  // ── Macro & rates ──────────────────────────────────────────────────────────
  // These carry a `unit` (so the app formats them as %/points/score, not "$…"),
  // an optional non-Yahoo `source`, and chart range hints. `unit` is also the
  // flag the UI uses to switch a card into "indicator" mode (explanation card,
  // unit-aware price block, no fundamentals/news).
  { key: 'US:^TNX', ticker: '^TNX', market: 'US', label: '10-Year Treasury Yield', short: 'US10Y', decimals: 2, invertColor: false,
    group: 'macro', unit: 'pct',   defaultRange: '1y' },
  { key: 'US:DX-Y.NYB', ticker: 'DX-Y.NYB', market: 'US', label: 'U.S. Dollar Index (DXY)', short: 'DXY', decimals: 2, invertColor: false,
    group: 'macro', unit: 'index', defaultRange: '1y' },
  { key: 'US:^DJT', ticker: '^DJT', market: 'US', label: 'Dow Jones Transports (DJT)', short: 'DJT', decimals: 0, invertColor: false,
    group: 'macro', unit: 'index', defaultRange: '1y' },
  { key: 'MACRO:FEDFUNDS', ticker: 'FEDFUNDS', market: 'MACRO', label: 'Federal Funds Rate', short: 'FEDFUNDS', decimals: 2, invertColor: false,
    group: 'macro', unit: 'pct',   source: 'fred', fredSeries: 'DFF',       fredTransform: 'level',      defaultRange: '1y', chartRanges: ['3mo','6mo','1y','5y','max'] },
  { key: 'MACRO:CPI', ticker: 'CPI', market: 'MACRO', label: 'Inflation — CPI (YoY)', short: 'CPI', decimals: 1, invertColor: false,
    group: 'macro', unit: 'pct',   source: 'fred', fredSeries: 'CPIAUCSL',  fredTransform: 'yoy',        defaultRange: '5y', chartRanges: ['1y','5y','max'] },
  { key: 'MACRO:NFP', ticker: 'NFP', market: 'MACRO', label: 'Non-Farm Payrolls', short: 'NFP', decimals: 0, invertColor: false,
    group: 'macro', unit: 'k_jobs', source: 'fred', fredSeries: 'PAYEMS',   fredTransform: 'mom_change', defaultRange: '5y', chartRanges: ['1y','5y','max'] },
  { key: 'MACRO:GLI', ticker: 'GLI', market: 'MACRO', label: 'Global Liquidity (proxy)', short: 'GLI', decimals: 2, invertColor: false,
    group: 'macro', unit: 'usd_t', source: 'gli',                                                        defaultRange: '5y', chartRanges: ['1y','5y','max'] },
  { key: 'MACRO:FNG', ticker: 'FNG', market: 'MACRO', label: 'Fear & Greed (VIX-based)', short: 'F&G', decimals: 0, invertColor: false,
    group: 'macro', unit: 'score', source: 'vixmood',                                                    defaultRange: '1y', chartRanges: ['1mo','3mo','6mo','1y','5y','max'] },
];
const RIBBON_CATALOG_MAP = Object.fromEntries(RIBBON_CATALOG.map(r => [r.key, r]));

// Plain-English deep-dives shown on each indicator's card. Kept short and
// jargon-light on purpose — the goal is to help a retail investor understand
// what the number means and how to read it. Keyed by the catalog `key`.
const INDICATOR_INFO = {
  'US:^TNX': {
    what: "The interest rate the U.S. government pays to borrow money for 10 years. It's the world's benchmark “risk-free” rate — it sets the tone for mortgages, loans, and how every other asset (stocks included) gets valued.",
    interpret: "Rising yields make borrowing pricier and bonds more competitive with stocks — usually a headwind, especially for expensive growth names. Falling yields mean cheaper money and are generally supportive for stocks. Watch the trend more than today's exact number.",
    levels: [{ label: 'Low', range: 'below 3%' }, { label: 'Normal (recent years)', range: '3–4.5%' }, { label: 'Elevated', range: 'above 5%' }]
  },
  'US:DX-Y.NYB': {
    what: "Measures the U.S. dollar's strength against a basket of major currencies (euro, yen, pound and others). Around 100 is the long-run baseline.",
    interpret: "A rising dollar (higher DXY) tends to pressure commodities like gold and oil, emerging markets, and U.S. companies that earn a lot overseas. A falling dollar is usually a tailwind for those same assets.",
    levels: [{ label: 'Weak', range: 'below ~95' }, { label: 'Neutral', range: '~100' }, { label: 'Strong', range: 'above ~105' }]
  },
  'US:^DJT': {
    what: "Tracks 20 major U.S. transport companies — airlines, railroads, trucking and delivery firms. Because they physically move goods, they're an early read on real economic activity.",
    interpret: "When transports rise alongside the broader market it confirms a healthy economy (the old “Dow Theory”). When they fall or lag while the Dow keeps climbing, it can be an early warning that growth is slowing."
  },
  'MACRO:FEDFUNDS': {
    what: "The Federal Reserve's key short-term interest rate — what U.S. banks charge each other overnight. The Fed raises it to cool inflation and cuts it to support growth. (Shown here is the effective rate; the Fed actually sets a target range.)",
    interpret: "Higher rates make borrowing more expensive and slow the economy — generally a headwind for stocks, especially growth. Lower rates mean cheaper money and are usually supportive. Markets care most about the direction and the Fed's next likely move."
  },
  'MACRO:CPI': {
    what: "The main inflation gauge: how much prices for everyday goods and services have risen over the past 12 months (year-over-year). Updated monthly.",
    interpret: "The Fed targets about 2%. Hotter CPI pushes the Fed toward higher rates (a headwind for stocks and bonds); cooling CPI gives the Fed room to ease, which markets usually welcome.",
    levels: [{ label: 'Fed target', range: '~2%' }, { label: 'Elevated', range: '3–5%' }, { label: 'Hot', range: 'above 5%' }]
  },
  'MACRO:NFP': {
    what: "The number of jobs the U.S. economy added (or lost) last month, excluding farms. Released the first Friday of each month — one of the most market-moving data points there is.",
    interpret: "Strong job growth signals a healthy economy, but if it runs too hot it can keep the Fed hawkish (rates higher for longer). Weak or negative payrolls point to a slowing economy and can push the Fed to cut. Markets judge it against expectations.",
    levels: [{ label: 'Soft', range: 'below ~100K' }, { label: 'Solid', range: '~150–250K' }, { label: 'Hot', range: 'above ~300K' }]
  },
  'MACRO:GLI': {
    what: "A transparent proxy for “global liquidity” — the combined balance sheets of the world's three biggest central banks (U.S. Fed, European Central Bank, Bank of Japan), converted to U.S. dollars. (A do-it-yourself proxy, not the proprietary CrossBorder Capital index.)",
    interpret: "Rising liquidity (central banks expanding) tends to lift risk assets — stocks, crypto, gold. Falling liquidity (tightening / quantitative tightening) is often a headwind. Think of it as a slow-moving tide: watch the direction over months, not days."
  },
  'MACRO:FNG': {
    what: "A 0–100 market-mood gauge built from the VIX (Wall Street's “fear index”): 0 = extreme fear, 100 = extreme greed. A transparent VIX-based stand-in for the popular Fear & Greed gauge.",
    interpret: "Extreme fear (low readings) often marks moments of maximum pessimism — historically closer to bottoms than tops. Extreme greed (high readings) suggests complacency and can precede pullbacks. The classic contrarian rule: be cautious when others are greedy, look for opportunity when others are fearful. Use it as a sentiment check, not a precise timing tool.",
    levels: [{ label: 'Extreme fear', range: '0–24' }, { label: 'Neutral', range: '~50' }, { label: 'Extreme greed', range: '76–100' }]
  }
};

// Scheduled 2026 central-bank decision days + recurring data, as an offline
// baseline. Dates are published a year ahead; refresh this list annually. When a
// Perplexity key is set, live AI events are merged in and take precedence.
const BUILTIN_MACRO_2026 = [
  { date: '2026-01-28', title: 'FOMC rate decision', type: 'Fed' },
  { date: '2026-03-18', title: 'FOMC rate decision + projections', type: 'Fed' },
  { date: '2026-04-29', title: 'FOMC rate decision', type: 'Fed' },
  { date: '2026-06-17', title: 'FOMC rate decision + projections', type: 'Fed' },
  { date: '2026-07-29', title: 'FOMC rate decision', type: 'Fed' },
  { date: '2026-09-16', title: 'FOMC rate decision + projections', type: 'Fed' },
  { date: '2026-10-28', title: 'FOMC rate decision', type: 'Fed' },
  { date: '2026-12-09', title: 'FOMC rate decision + projections', type: 'Fed' },
  { date: '2026-01-23', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-03-19', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-04-28', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-06-16', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-07-31', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-09-18', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-10-30', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-12-18', title: 'Bank of Japan policy decision', type: 'BOJ' },
  { date: '2026-01-29', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-03-12', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-04-30', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-06-04', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-07-16', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-09-10', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-10-29', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-12-17', title: 'ECB monetary policy decision', type: 'ECB' },
  { date: '2026-02-05', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-03-19', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-05-07', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-06-18', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-08-06', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-09-17', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-11-05', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-12-17', title: 'Bank of England Bank Rate decision', type: 'BOE' },
  { date: '2026-01-29', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' },
  { date: '2026-03-19', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' },
  { date: '2026-05-21', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' },
  { date: '2026-07-23', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' },
  { date: '2026-09-17', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' },
  { date: '2026-11-19', title: 'SARB MPC rate decision (South Africa)', type: 'SARB' }
];

  // Rules tab: pre-written trim rules, thesis-break triggers, and SA tax-year
  // discipline. Sections keyed by `id`; a bullet is { text } or { strong, text }
  // (a bold lead-in + text). Rendered by RulesView via the `ruleSection` helper.
  const RULES = [
    { id: 'trim', heading: 'Trim rules', bullets: [
      { strong: '+100% gain',            text: ' \u2014 trim 25% of position, bank profits' },
      { strong: '+150% gain',            text: ' \u2014 trim another 20% of remainder' },
      { strong: '+200% gain',            text: ' \u2014 trim another 20%, let the rest ride' },
      { strong: '-20% from cost',        text: ' \u2014 re-examine thesis, never average down without fresh conviction' },
      { strong: 'Position >12% of book', text: ' \u2014 trim to 10% regardless of gain' },
    ]},
    { id: 'thesisBreak', heading: 'Thesis-break triggers', bullets: [
      { text: 'Hyperscaler capex cut by top-3 player (MSFT, GOOGL, META, AMZN, ORCL)' },
      { text: 'Core CPI above 3.2% for two consecutive prints' },
      { text: 'Brent above $120 \u2014 consumer weakness trigger' },
      { text: 'VOO drawdown >15% from buy-zone \u2014 deploy all cash' },
      { text: 'Any position where CEO reneges on publicly-stated commitment (the MSTR lesson)' },
    ]},
    { id: 'saTax', heading: 'SA tax-year discipline', bullets: [
      { text: 'Tax year ends 28 February. Split disposals across 28 Feb + 1 March for two annual R40k CGT exclusions.' },
      { text: 'Combined shelter: up to R80k of gains untaxed per year.' },
      { text: 'At 40% marginal rate with 40% inclusion, each exclusion = ~R12,800 saved.' },
      { text: 'Keep broker IT3(c) certificates for each tax year.' },
    ]},
  ];

const SECTOR_ETF = {
  'Technology':              { etf: 'XLK',  name: 'Technology Select Sector' },
  'Communication Services':  { etf: 'XLC',  name: 'Communication Services' },
  'Consumer Cyclical':       { etf: 'XLY',  name: 'Consumer Discretionary' },
  'Consumer Defensive':      { etf: 'XLP',  name: 'Consumer Staples' },
  'Energy':                  { etf: 'XLE',  name: 'Energy Select Sector' },
  'Financial Services':      { etf: 'XLF',  name: 'Financial Select Sector' },
  'Financials':             { etf: 'XLF',  name: 'Financial Select Sector' },
  'Healthcare':              { etf: 'XLV',  name: 'Health Care Select Sector' },
  'Industrials':             { etf: 'XLI',  name: 'Industrial Select Sector' },
  'Basic Materials':         { etf: 'XLB',  name: 'Materials Select Sector' },
  'Materials':               { etf: 'XLB',  name: 'Materials Select Sector' },
  'Real Estate':             { etf: 'XLRE', name: 'Real Estate Select Sector' },
  'Utilities':               { etf: 'XLU',  name: 'Utilities Select Sector' },
};
const SECTOR_TREND_WINDOWS = [
  { key: '1W', days: 7 },
  { key: '1M', days: 30 },
  { key: '1Y', days: 365 },
  { key: '2Y', days: 730 },
  { key: '3Y', days: 1095 },
  { key: '5Y', days: 1825 },
];
const SECTOR_FWD_PE = {
  'technology': 27, 'information technology': 27,
  'communication services': 19, 'communications': 19,
  'consumer cyclical': 22, 'consumer discretionary': 22,
  'consumer defensive': 19, 'consumer staples': 19,
  'healthcare': 17, 'health care': 17,
  'financial services': 15, 'financials': 15, 'financial': 15,
  'industrials': 20, 'industrial': 20,
  'energy': 12,
  'basic materials': 16, 'materials': 16,
  'real estate': 18,
  'utilities': 17,
};

// UI config: markets & display currencies (client-only, pure data)
const MARKETS = [
  { value: 'US',   label: 'US',   country: 'USA',          exchange: 'NYSE / NASDAQ' },
  { value: 'JSE',  label: 'JSE',  country: 'South Africa',  exchange: 'JSE' },
  { value: 'TFSA', label: 'TFSA', country: 'South Africa',  exchange: 'JSE (Tax-Free)' },
  { value: 'LSE', label: 'LSE', country: 'UK',          exchange: 'London (LSE)' },
  { value: 'ASX', label: 'ASX', country: 'Australia',   exchange: 'ASX' },
  { value: 'FRA', label: 'FRA', country: 'Germany',     exchange: 'XETRA Frankfurt' },
  { value: 'PAR', label: 'PAR', country: 'France',      exchange: 'Euronext Paris' },
  { value: 'AMS', label: 'AMS', country: 'Netherlands', exchange: 'Euronext Amsterdam' },
  { value: 'CRYPTO', label: 'Crypto', country: 'Crypto', exchange: 'Spot \u00b7 24/7' },
];
const DISPLAY_CURRENCIES = [
  { code: 'USD', sym: '$',  label: 'US Dollar' },
  { code: 'ZAR', sym: 'R',  label: 'South African Rand' },
  { code: 'GBP', sym: '\u00a3', label: 'British Pound' },
  { code: 'AUD', sym: 'A$', label: 'Australian Dollar' },
  { code: 'EUR', sym: '\u20ac', label: 'Euro' },
];
const CURRENCY_SYMBOLS = { USD: '$', ZAR: 'R', GBP: '\u00a3', AUD: 'A$', EUR: '\u20ac' };

// Rotation tab copy. Verdict titles keyed by classifyRotation()'s verdict; the
// dynamic detail sentence is built by PBCore.rotationSummary(). Phase labels
// keyed by marketSession()'s phase. ASCII only (no build step; special glyphs
// would need \uXXXX escapes).
const ROTATION_COPY = {
  verdicts: {
    inflow: 'Money is flowing into the market',
    outflow: 'Money is leaving the market',
    rotation: 'Money is rotating, not leaving',
    'inflow-rotation': 'Inflows, with rotation underneath',
    'outflow-rotation': 'Outflows, with rotation underneath',
    mixed: 'Mixed - no clear direction',
    quiet: 'Quiet session',
  },
  phase: {
    pre: 'Pre-market',
    open: 'Market open',
    post: 'After hours',
    closed: 'Closed - last session',
  },
  method: 'Flow estimate = index weight x day move (market-cap delta). A price-based proxy, not traded volume.',
};
// Shortened sector names for the tight flow-diagram blocks and legend chips.
const ROTATION_SECTOR_SHORT = {
  'Technology': 'Tech',
  'Communication Services': 'Comm Svcs',
  'Consumer Cyclical': 'Cons Cyclical',
  'Consumer Defensive': 'Cons Defensive',
  'Financial Services': 'Financials',
  'Financials': 'Financials',
  'Healthcare': 'Healthcare',
  'Industrials': 'Industrials',
  'Basic Materials': 'Materials',
  'Materials': 'Materials',
  'Real Estate': 'Real Estate',
  'Energy': 'Energy',
  'Utilities': 'Utilities',
};

// Instrument logo pack. GENERATED — do not hand-edit; run `node tools/build-logos.mjs`.
// Keys are `MARKET:TICKER`. `f` = filename under ./logos/, `b` = bleed (art is
// its own tile), `k` = needs a white backing. No flag = plain, no tile.
// <<< LOGO_MANIFEST_START
const LOGO_MANIFEST = {
  "AMS:AALB": {"c":"#7f0b1f"},
  "AMS:ABN": {"c":"#06847a"},
  "AMS:AD": {"f":"AMS-AD.png"},
  "AMS:ADYEN": {"f":"AMS-ADYEN.png"},
  "AMS:AGN": {"c":"#841906"},
  "AMS:AKZA": {"f":"AMS-AKZA.png"},
  "AMS:ASM": {"f":"AMS-ASM.png"},
  "AMS:ASML": {"f":"AMS-ASML.png"},
  "AMS:ASRNL": {"f":"AMS-ASRNL.png"},
  "AMS:BESI": {"c":"#068448"},
  "AMS:EXO": {"c":"#083d81"},
  "AMS:GLPG": {"f":"AMS-GLPG.png"},
  "AMS:IMCD": {"c":"#065e84"},
  "AMS:INGA": {"f":"AMS-INGA.png"},
  "AMS:JDEP": {"f":"AMS-JDEP.png"},
  "AMS:KPN": {"f":"AMS-KPN.png"},
  "AMS:MT": {"f":"AMS-MT.png"},
  "AMS:NN": {"f":"AMS-NN.png"},
  "AMS:OCI": {"f":"AMS-OCI.png"},
  "AMS:PHIA": {"f":"AMS-PHIA.png"},
  "AMS:PNL": {"f":"AMS-PNL.png"},
  "AMS:RAND": {"f":"AMS-RAND.png"},
  "AMS:REN": {"f":"AMS-REN.png"},
  "AMS:TKWY": {"c":"#844906"},
  "AMS:UMG": {"f":"AMS-UMG.png"},
  "AMS:UNA": {"f":"AMS-UNA.png"},
  "AMS:WKL": {"f":"AMS-WKL.png"},
  "ASX:A2M": {"f":"ASX-A2M.png"},
  "ASX:ALL": {"c":"#0b437f"},
  "ASX:ALU": {"f":"ASX-ALU.png"},
  "ASX:AMC": {"f":"ASX-AMC.png"},
  "ASX:ANZ": {"f":"ASX-ANZ.png"},
  "ASX:APT": {"f":"ASX-APT.png"},
  "ASX:APX": {"f":"ASX-APX.png"},
  "ASX:ASX": {"f":"ASX-ASX.png"},
  "ASX:AZJ": {"f":"ASX-AZJ.png"},
  "ASX:BHP": {"f":"ASX-BHP.png"},
  "ASX:BXB": {"c":"#064d84"},
  "ASX:CAR": {"c":"#064684"},
  "ASX:CBA": {"f":"ASX-CBA.png"},
  "ASX:COH": {"c":"#846b06"},
  "ASX:COL": {"f":"ASX-COL.png"},
  "ASX:CPU": {"c":"#84065d"},
  "ASX:CSL": {"c":"#7c0e14"},
  "ASX:DMP": {"c":"#065484"},
  "ASX:EVN": {"c":"#6c2e1e"},
  "ASX:FMG": {"f":"ASX-FMG.png"},
  "ASX:GMG": {"f":"ASX-GMG.png"},
  "ASX:HVN": {"c":"#065084"},
  "ASX:IAG": {"f":"ASX-IAG.png"},
  "ASX:IGO": {"f":"ASX-IGO.png"},
  "ASX:JBH": {"f":"ASX-JBH.png"},
  "ASX:JHX": {"f":"ASX-JHX.png"},
  "ASX:LYC": {"c":"#107279"},
  "ASX:MFG": {"f":"ASX-MFG.png"},
  "ASX:MGR": {"c":"#062984"},
  "ASX:MIN": {"f":"ASX-MIN.png"},
  "ASX:NAB": {"f":"ASX-NAB.png"},
  "ASX:NEM": {"c":"#202f6a"},
  "ASX:NST": {"f":"ASX-NST.png"},
  "ASX:ORG": {"f":"ASX-ORG.png"},
  "ASX:PLS": {"f":"ASX-PLS.png"},
  "ASX:PME": {"c":"#821308"},
  "ASX:QAN": {"f":"ASX-QAN.png"},
  "ASX:QBE": {"f":"ASX-QBE.png"},
  "ASX:REA": {"f":"ASX-REA.png"},
  "ASX:RHC": {"c":"#134776"},
  "ASX:RIO": {"c":"#711919"},
  "ASX:RMD": {"f":"ASX-RMD.png"},
  "ASX:S32": {"c":"#847406"},
  "ASX:SCG": {"c":"#800a16"},
  "ASX:SEK": {"f":"ASX-SEK.png"},
  "ASX:SGP": {"c":"#062f84"},
  "ASX:SHL": {"f":"ASX-SHL.png"},
  "ASX:STO": {"f":"ASX-STO.png"},
  "ASX:SUN": {"f":"ASX-SUN.png"},
  "ASX:TCL": {"f":"ASX-TCL.png"},
  "ASX:TLS": {"f":"ASX-TLS.png"},
  "ASX:TWE": {"c":"#67232b"},
  "ASX:WBC": {"f":"ASX-WBC.png"},
  "ASX:WDS": {"f":"ASX-WDS.png"},
  "ASX:WES": {"c":"#06842a"},
  "ASX:WHC": {"f":"ASX-WHC.png"},
  "ASX:WOW": {"f":"ASX-WOW.png"},
  "ASX:WTC": {"f":"ASX-WTC.png"},
  "ASX:XRO": {"f":"ASX-XRO.png"},
  "ASX:ZIP": {"f":"ASX-ZIP.png"},
  "CRYPTO:AAVE": {"f":"CRYPTO-AAVE.png"},
  "CRYPTO:ADA": {"f":"CRYPTO-ADA.png"},
  "CRYPTO:ALGO": {"f":"CRYPTO-ALGO.png"},
  "CRYPTO:ATOM": {"f":"CRYPTO-ATOM.png"},
  "CRYPTO:AVAX": {"f":"CRYPTO-AVAX.png"},
  "CRYPTO:BCH": {"f":"CRYPTO-BCH.png"},
  "CRYPTO:BNB": {"f":"CRYPTO-BNB.png"},
  "CRYPTO:BTC": {"f":"CRYPTO-BTC.png"},
  "CRYPTO:DOGE": {"f":"CRYPTO-DOGE.png"},
  "CRYPTO:DOT": {"f":"CRYPTO-DOT.png"},
  "CRYPTO:ETC": {"f":"CRYPTO-ETC.png"},
  "CRYPTO:ETH": {"f":"CRYPTO-ETH.png"},
  "CRYPTO:FIL": {"f":"CRYPTO-FIL.png"},
  "CRYPTO:LINK": {"f":"CRYPTO-LINK.png"},
  "CRYPTO:LTC": {"f":"CRYPTO-LTC.png"},
  "CRYPTO:MATIC": {"f":"CRYPTO-MATIC.png"},
  "CRYPTO:MKR": {"f":"CRYPTO-MKR.png"},
  "CRYPTO:SOL": {"f":"CRYPTO-SOL.png"},
  "CRYPTO:TRX": {"f":"CRYPTO-TRX.png"},
  "CRYPTO:UNI": {"f":"CRYPTO-UNI.png"},
  "CRYPTO:USDC": {"f":"CRYPTO-USDC.png"},
  "CRYPTO:USDT": {"f":"CRYPTO-USDT.png"},
  "CRYPTO:XLM": {"f":"CRYPTO-XLM.png"},
  "CRYPTO:XMR": {"f":"CRYPTO-XMR.png"},
  "CRYPTO:XRP": {"f":"CRYPTO-XRP.png"},
  "CRYPTO:XTZ": {"f":"CRYPTO-XTZ.png"},
  "FRA:1COV": {"f":"FRA-1COV.png"},
  "FRA:AIR": {"f":"FRA-AIR.png"},
  "FRA:ALV": {"f":"FRA-ALV.png"},
  "FRA:BAS": {"f":"FRA-BAS.png"},
  "FRA:BAYN": {"f":"FRA-BAYN.png"},
  "FRA:BEI": {"c":"#0d207d"},
  "FRA:BMW": {"f":"FRA-BMW.png"},
  "FRA:BNR": {"f":"FRA-BNR.png"},
  "FRA:CBK": {"f":"FRA-CBK.png"},
  "FRA:CON": {"c":"#845706"},
  "FRA:COV": {"f":"FRA-COV.png"},
  "FRA:DBK": {"f":"FRA-DBK.png"},
  "FRA:DPW": {"f":"FRA-DPW.png"},
  "FRA:DTE": {"f":"FRA-DTE.png"},
  "FRA:ENR": {"f":"FRA-ENR.png"},
  "FRA:EOAN": {"f":"FRA-EOAN.png"},
  "FRA:FRE": {"f":"FRA-FRE.png"},
  "FRA:HEI": {"f":"FRA-HEI.png"},
  "FRA:HEN3": {"f":"FRA-HEN3.png"},
  "FRA:HFG": {"f":"FRA-HFG.png"},
  "FRA:HNR1": {"f":"FRA-HNR1.png"},
  "FRA:HOT": {"f":"FRA-HOT.png"},
  "FRA:IFX": {"c":"#064b84"},
  "FRA:LEG": {"f":"FRA-LEG.png"},
  "FRA:LIN": {"f":"FRA-LIN.png"},
  "FRA:MBG": {"f":"FRA-MBG.png"},
  "FRA:MRK": {"f":"FRA-MRK.png"},
  "FRA:MUV2": {"f":"FRA-MUV2.png"},
  "FRA:P911": {"f":"FRA-P911.png"},
  "FRA:PAH3": {"f":"FRA-PAH3.png"},
  "FRA:PORS": {"f":"FRA-PORS.png"},
  "FRA:PUM": {"f":"FRA-PUM.png"},
  "FRA:RWE": {"f":"FRA-RWE.png"},
  "FRA:SAP": {"c":"#064084"},
  "FRA:SHL": {"f":"FRA-SHL.png"},
  "FRA:SIE": {"f":"FRA-SIE.png"},
  "FRA:SY1": {"c":"#731616"},
  "FRA:VNA": {"c":"#245765"},
  "FRA:VOW3": {"f":"FRA-VOW3.png"},
  "FRA:ZAL": {"c":"#843906"},
  "JSE:AAGEET": {"c":"#7e0c23"},
  "JSE:AASAET": {"c":"#7e0c23"},
  "JSE:ABG": {"f":"JSE-ABG.png"},
  "JSE:ABSP": {"c":"#701a21"},
  "JSE:ADH": {"c":"#781115"},
  "JSE:ADV": {"c":"#781115"},
  "JSE:AEG": {"f":"JSE-AEG.png"},
  "JSE:AEL": {"f":"JSE-AEL.png"},
  "JSE:AFE": {"f":"JSE-AFE.png"},
  "JSE:AFH": {"f":"JSE-AFH.png"},
  "JSE:AGL": {"c":"#322862"},
  "JSE:AIP": {"c":"#0f687a"},
  "JSE:ALT": {"f":"JSE-ALT.png"},
  "JSE:AMS": {"f":"JSE-AMS.png"},
  "JSE:ANG": {"f":"JSE-ANG.png"},
  "JSE:APACXJ": {"f":"JSE-APACXJ.png"},
  "JSE:APF": {"f":"JSE-APF.png"},
  "JSE:APH": {"f":"JSE-APH.png"},
  "JSE:APN": {"f":"JSE-APN.png"},
  "JSE:ARL": {"f":"JSE-ARL.png"},
  "JSE:ART": {"f":"JSE-ART.png"},
  "JSE:ASHGEQ": {"f":"JSE-ASHGEQ.png"},
  "JSE:ASHMID": {"f":"JSE-ASHMID.png"},
  "JSE:ASHT40": {"f":"JSE-ASHT40.png"},
  "JSE:AVI": {"f":"JSE-AVI.png"},
  "JSE:BAT": {"f":"JSE-BAT.png"},
  "JSE:BAW": {"c":"#1a4d70"},
  "JSE:BGA": {"c":"#701a21"},
  "JSE:BHG": {"f":"JSE-BHG.png"},
  "JSE:BHP": {"f":"JSE-BHP.png"},
  "JSE:BID": {"c":"#281e6b"},
  "JSE:BLU": {"f":"JSE-BLU.png"},
  "JSE:BTI": {"f":"JSE-BTI.png"},
  "JSE:BVT": {"f":"JSE-BVT.png"},
  "JSE:BWN": {"f":"JSE-BWN.png"},
  "JSE:BYI": {"f":"JSE-BYI.png"},
  "JSE:CARTBL": {"c":"#7e0c23"},
  "JSE:CFR": {"f":"JSE-CFR.png"},
  "JSE:CGR": {"c":"#695e21"},
  "JSE:CLS": {"c":"#064e84"},
  "JSE:CMH": {"f":"JSE-CMH.png"},
  "JSE:CML": {"f":"JSE-CML.png"},
  "JSE:COGEM": {"f":"JSE-COGEM.png"},
  "JSE:COGES": {"f":"JSE-COGES.png"},
  "JSE:COGMAN": {"f":"JSE-COGMAN.png"},
  "JSE:COGOE": {"f":"JSE-COGOE.png"},
  "JSE:COOPTI": {"f":"JSE-COOPTI.png"},
  "JSE:CPI": {"c":"#065784"},
  "JSE:CPIP": {"c":"#065784"},
  "JSE:CSB": {"c":"#7f0c0b"},
  "JSE:CSEW40": {"f":"JSE-CSEW40.png"},
  "JSE:CSNDQ": {"f":"JSE-CSNDQ.png"},
  "JSE:CSP500": {"f":"JSE-CSP500.png"},
  "JSE:CSPROP": {"f":"JSE-CSPROP.png"},
  "JSE:CSTOP50": {"f":"JSE-CSTOP50.png"},
  "JSE:CTOP50": {"f":"JSE-CTOP50.png"},
  "JSE:DCP": {"c":"#286234"},
  "JSE:DIVTRX": {"f":"JSE-DIVTRX.png"},
  "JSE:DSY": {"c":"#147631"},
  "JSE:EASY5": {"c":"#7e0c23"},
  "JSE:EASYAI": {"c":"#7e0c23"},
  "JSE:EASYBF": {"c":"#7e0c23"},
  "JSE:EASYGE": {"c":"#7e0c23"},
  "JSE:EMI": {"f":"JSE-EMI.png"},
  "JSE:ENX": {"f":"JSE-ENX.png"},
  "JSE:EOH": {"f":"JSE-EOH.png"},
  "JSE:EQU": {"f":"JSE-EQU.png"},
  "JSE:ETF500": {"f":"JSE-ETF500.png"},
  "JSE:ETF5IT": {"f":"JSE-ETF5IT.png"},
  "JSE:ETFBND": {"f":"JSE-ETFBND.png"},
  "JSE:ETFEMA": {"f":"JSE-ETFEMA.png"},
  "JSE:ETFGGB": {"f":"JSE-ETFGGB.png"},
  "JSE:ETFGLD": {"f":"JSE-ETFGLD.png"},
  "JSE:ETFGRE": {"f":"JSE-ETFGRE.png"},
  "JSE:ETFPLD": {"f":"JSE-ETFPLD.png"},
  "JSE:ETFPLT": {"f":"JSE-ETFPLT.png"},
  "JSE:ETFRHO": {"f":"JSE-ETFRHO.png"},
  "JSE:ETFSAP": {"f":"JSE-ETFSAP.png"},
  "JSE:ETFSRI": {"f":"JSE-ETFSRI.png"},
  "JSE:ETFSWX": {"f":"JSE-ETFSWX.png"},
  "JSE:ETFT40": {"f":"JSE-ETFT40.png"},
  "JSE:ETFWLD": {"f":"JSE-ETFWLD.png"},
  "JSE:EXX": {"f":"JSE-EXX.png"},
  "JSE:FBR": {"f":"JSE-FBR.png"},
  "JSE:FFA": {"f":"JSE-FFA.png"},
  "JSE:FFB": {"f":"JSE-FFB.png"},
  "JSE:FNBEMG": {"c":"#764d14"},
  "JSE:FNBINF": {"c":"#764d14"},
  "JSE:FNBMID": {"c":"#764d14"},
  "JSE:FNBT40": {"c":"#764d14"},
  "JSE:FSR": {"f":"JSE-FSR.png"},
  "JSE:GFI": {"c":"#0b3b7e"},
  "JSE:GLOBAL": {"f":"JSE-GLOBAL.png"},
  "JSE:GLODIV": {"f":"JSE-GLODIV.png"},
  "JSE:GLPROP": {"f":"JSE-GLPROP.png"},
  "JSE:GML": {"f":"JSE-GML.png"},
  "JSE:GND": {"f":"JSE-GND.png"},
  "JSE:GPI": {"c":"#1a3b70"},
  "JSE:GRT": {"f":"JSE-GRT.png"},
  "JSE:HAR": {"c":"#84060e"},
  "JSE:HCI": {"c":"#135b77"},
  "JSE:HMN": {"f":"JSE-HMN.png"},
  "JSE:HYP": {"f":"JSE-HYP.png"},
  "JSE:INCOME": {"f":"JSE-INCOME.png"},
  "JSE:ITE": {"f":"JSE-ITE.png"},
  "JSE:IVT": {"f":"JSE-IVT.png"},
  "JSE:JSE": {"f":"JSE-JSE.png"},
  "JSE:KAP": {"f":"JSE-KAP.png"},
  "JSE:KRO": {"f":"JSE-KRO.png"},
  "JSE:KST": {"f":"JSE-KST.png"},
  "JSE:LBR": {"f":"JSE-LBR.png"},
  "JSE:LEW": {"c":"#6f1b1f"},
  "JSE:LHC": {"f":"JSE-LHC.png"},
  "JSE:MCG": {"c":"#815208"},
  "JSE:MND": {"f":"JSE-MND.png"},
  "JSE:MNP": {"f":"JSE-MNP.png"},
  "JSE:MRP": {"c":"#6a1f27"},
  "JSE:MSP": {"c":"#676f1a"},
  "JSE:MTA": {"f":"JSE-MTA.png"},
  "JSE:MTH": {"c":"#840627"},
  "JSE:MTM": {"f":"JSE-MTM.png"},
  "JSE:MTN": {"f":"JSE-MTN.png"},
  "JSE:MUR": {"c":"#736217"},
  "JSE:NED": {"c":"#068459"},
  "JSE:NPN": {"f":"JSE-NPN.png"},
  "JSE:NRP": {"f":"JSE-NRP.png"},
  "JSE:NTC": {"c":"#625128"},
  "JSE:OCE": {"f":"JSE-OCE.png"},
  "JSE:OCT": {"f":"JSE-OCT.png"},
  "JSE:OMU": {"c":"#2b6327"},
  "JSE:ORN": {"c":"#804909"},
  "JSE:OUT": {"f":"JSE-OUT.png"},
  "JSE:PAN": {"f":"JSE-PAN.png"},
  "JSE:PCWGE": {"f":"JSE-PCWGE.png"},
  "JSE:PIK": {"f":"JSE-PIK.png"},
  "JSE:PPC": {"f":"JSE-PPC.png"},
  "JSE:PPE": {"c":"#846806"},
  "JSE:PPH": {"f":"JSE-PPH.png"},
  "JSE:PRX": {"f":"JSE-PRX.png"},
  "JSE:QLT": {"f":"JSE-QLT.png"},
  "JSE:RBX": {"f":"JSE-RBX.png"},
  "JSE:RCL": {"f":"JSE-RCL.png"},
  "JSE:RDF": {"c":"#7c0e12"},
  "JSE:REM": {"f":"JSE-REM.png"},
  "JSE:RES": {"f":"JSE-RES.png"},
  "JSE:RLO": {"c":"#223868"},
  "JSE:RMI": {"f":"JSE-RMI.png"},
  "JSE:RWDVF": {"c":"#813009"},
  "JSE:RWGPR": {"c":"#813009"},
  "JSE:RWINC": {"c":"#813009"},
  "JSE:S32": {"c":"#847406"},
  "JSE:SAC": {"f":"JSE-SAC.png"},
  "JSE:SAP": {"f":"JSE-SAP.png"},
  "JSE:SBK": {"f":"JSE-SBK.png"},
  "JSE:SEA": {"f":"JSE-SEA.png"},
  "JSE:SEP": {"f":"JSE-SEP.png"},
  "JSE:SHC": {"f":"JSE-SHC.png"},
  "JSE:SHG": {"c":"#6c1d1f"},
  "JSE:SHP": {"f":"JSE-SHP.png"},
  "JSE:SNT": {"c":"#826208"},
  "JSE:SOL": {"f":"JSE-SOL.png"},
  "JSE:SPG": {"f":"JSE-SPG.png"},
  "JSE:SSS": {"f":"JSE-SSS.png"},
  "JSE:SSU": {"f":"JSE-SSU.png"},
  "JSE:SSW": {"f":"JSE-SSW.png"},
  "JSE:SUI": {"f":"JSE-SUI.png"},
  "JSE:SUR": {"f":"JSE-SUR.png"},
  "JSE:TBS": {"c":"#7f0b0f"},
  "JSE:TCP": {"f":"JSE-TCP.png"},
  "JSE:TFG": {"f":"JSE-TFG.png"},
  "JSE:TGA": {"f":"JSE-TGA.png"},
  "JSE:THA": {"c":"#840614"},
  "JSE:TKG": {"f":"JSE-TKG.png"},
  "JSE:TRU": {"f":"JSE-TRU.png"},
  "JSE:TSG": {"c":"#715919"},
  "JSE:VAL": {"f":"JSE-VAL.png"},
  "JSE:VKE": {"f":"JSE-VKE.png"},
  "JSE:VOD": {"c":"#840613"},
  "JSE:VUNGLE": {"f":"JSE-VUNGLE.png"},
  "JSE:WBO": {"f":"JSE-WBO.png"},
  "JSE:WNXT40": {"f":"JSE-WNXT40.png"},
  "JSE:WTOP20": {"f":"JSE-WTOP20.png"},
  "JSE:YRK": {"f":"JSE-YRK.png"},
  "JSE:ZED": {"f":"JSE-ZED.png"},
  "LSE:AAL": {"c":"#061784"},
  "LSE:ABF": {"c":"#7b0e27"},
  "LSE:ADM": {"c":"#840644"},
  "LSE:AHT": {"f":"LSE-AHT.png"},
  "LSE:AJB": {"f":"LSE-AJB.png"},
  "LSE:ANTO": {"f":"LSE-ANTO.png"},
  "LSE:AV": {"f":"LSE-AV.png"},
  "LSE:AZN": {"f":"LSE-AZN.png"},
  "LSE:BA": {"c":"#83071e"},
  "LSE:BAB": {"f":"LSE-BAB.png"},
  "LSE:BARC": {"c":"#066584"},
  "LSE:BATS": {"c":"#153675"},
  "LSE:BBOX": {"f":"LSE-BBOX.png"},
  "LSE:BDEV": {"f":"LSE-BDEV.png"},
  "LSE:BGEO": {"f":"LSE-BGEO.png"},
  "LSE:BKG": {"f":"LSE-BKG.png"},
  "LSE:BLND": {"f":"LSE-BLND.png"},
  "LSE:BME": {"f":"LSE-BME.png"},
  "LSE:BNZL": {"f":"LSE-BNZL.png"},
  "LSE:BP": {"f":"LSE-BP.png"},
  "LSE:BT-A": {"f":"LSE-BT-A.png"},
  "LSE:CBG": {"f":"LSE-CBG.png"},
  "LSE:CCH": {"f":"LSE-CCH.png"},
  "LSE:CNA": {"f":"LSE-CNA.png"},
  "LSE:CPG": {"f":"LSE-CPG.png"},
  "LSE:CRDA": {"f":"LSE-CRDA.png"},
  "LSE:CRH": {"f":"LSE-CRH.png"},
  "LSE:CTEC": {"f":"LSE-CTEC.png"},
  "LSE:DCC": {"c":"#282862"},
  "LSE:DRX": {"f":"LSE-DRX.png"},
  "LSE:ENQ": {"c":"#184b72"},
  "LSE:ENT": {"f":"LSE-ENT.png"},
  "LSE:EXPN": {"f":"LSE-EXPN.png"},
  "LSE:FRAS": {"f":"LSE-FRAS.png"},
  "LSE:FXPO": {"c":"#366a20"},
  "LSE:GRI": {"f":"LSE-GRI.png"},
  "LSE:GSK": {"f":"LSE-GSK.png"},
  "LSE:HBR": {"c":"#841f06"},
  "LSE:HIK": {"c":"#840906"},
  "LSE:HLMA": {"c":"#4e7b0f"},
  "LSE:HLN": {"c":"#237a10"},
  "LSE:HOC": {"f":"LSE-HOC.png"},
  "LSE:HSBA": {"f":"LSE-HSBA.png"},
  "LSE:HSX": {"f":"LSE-HSX.png"},
  "LSE:HWDN": {"c":"#840614"},
  "LSE:IAG": {"f":"LSE-IAG.png"},
  "LSE:ICG": {"f":"LSE-ICG.png"},
  "LSE:IGG": {"f":"LSE-IGG.png"},
  "LSE:III": {"f":"LSE-III.png"},
  "LSE:IMB": {"c":"#844106"},
  "LSE:IMI": {"f":"LSE-IMI.png"},
  "LSE:ITV": {"f":"LSE-ITV.png"},
  "LSE:KNOS": {"f":"LSE-KNOS.png"},
  "LSE:LAND": {"f":"LSE-LAND.png"},
  "LSE:LLOY": {"f":"LSE-LLOY.png"},
  "LSE:LSE": {"f":"LSE-LSE.png"},
  "LSE:LSEG": {"f":"LSE-LSEG.png"},
  "LSE:MNDI": {"f":"LSE-MNDI.png"},
  "LSE:MNG": {"f":"LSE-MNG.png"},
  "LSE:MRO": {"f":"LSE-MRO.png"},
  "LSE:NG": {"c":"#231971"},
  "LSE:NWG": {"c":"#4f1d6c"},
  "LSE:OCDO": {"f":"LSE-OCDO.png"},
  "LSE:OSB": {"c":"#283362"},
  "LSE:PETS": {"f":"LSE-PETS.png"},
  "LSE:PHNX": {"f":"LSE-PHNX.png"},
  "LSE:PHP": {"f":"LSE-PHP.png"},
  "LSE:PNN": {"f":"LSE-PNN.png"},
  "LSE:PRU": {"c":"#761a14"},
  "LSE:PSN": {"f":"LSE-PSN.png"},
  "LSE:PSON": {"c":"#1b0684"},
  "LSE:QQ": {"f":"LSE-QQ.png"},
  "LSE:REL": {"f":"LSE-REL.png"},
  "LSE:RIO": {"c":"#711919"},
  "LSE:RKT": {"f":"LSE-RKT.png"},
  "LSE:ROR": {"c":"#7c0e15"},
  "LSE:RR": {"f":"LSE-RR.png"},
  "LSE:RTO": {"c":"#7f0a0c"},
  "LSE:SBRY": {"c":"#844e06"},
  "LSE:SDR": {"f":"LSE-SDR.png"},
  "LSE:SDRC": {"f":"LSE-SDRC.png"},
  "LSE:SGE": {"c":"#068427"},
  "LSE:SGRO": {"f":"LSE-SGRO.png"},
  "LSE:SHEL": {"f":"LSE-SHEL.png"},
  "LSE:SMIN": {"c":"#065584"},
  "LSE:SN": {"f":"LSE-SN.png"},
  "LSE:SPX": {"f":"LSE-SPX.png"},
  "LSE:SSE": {"f":"LSE-SSE.png"},
  "LSE:STAN": {"f":"LSE-STAN.png"},
  "LSE:STJ": {"f":"LSE-STJ.png"},
  "LSE:SVT": {"f":"LSE-SVT.png"},
  "LSE:SXS": {"f":"LSE-SXS.png"},
  "LSE:TLW": {"f":"LSE-TLW.png"},
  "LSE:TSCO": {"c":"#840606"},
  "LSE:TUI": {"f":"LSE-TUI.png"},
  "LSE:TW": {"f":"LSE-TW.png"},
  "LSE:ULVR": {"f":"LSE-ULVR.png"},
  "LSE:UTG": {"f":"LSE-UTG.png"},
  "LSE:UU": {"c":"#068473"},
  "LSE:VOD": {"c":"#7e0c0c"},
  "LSE:WEIR": {"c":"#064684"},
  "LSE:WIZ": {"f":"LSE-WIZ.png"},
  "LSE:WPP": {"c":"#1c206e"},
  "LSE:WTB": {"f":"LSE-WTB.png"},
  "PAR:ACA": {"c":"#236366"},
  "PAR:AI": {"c":"#243e66"},
  "PAR:AIR": {"f":"PAR-AIR.png"},
  "PAR:ALO": {"f":"PAR-ALO.png"},
  "PAR:AMUN": {"f":"PAR-AMUN.png"},
  "PAR:ATO": {"f":"PAR-ATO.png"},
  "PAR:BN": {"f":"PAR-BN.png"},
  "PAR:BNP": {"f":"PAR-BNP.png"},
  "PAR:BVI": {"f":"PAR-BVI.png"},
  "PAR:CA": {"f":"PAR-CA.png"},
  "PAR:CAP": {"c":"#064784"},
  "PAR:CS": {"f":"PAR-CS.png"},
  "PAR:DG": {"f":"PAR-DG.png"},
  "PAR:DSY": {"f":"PAR-DSY.png"},
  "PAR:EDEN": {"f":"PAR-EDEN.png"},
  "PAR:EL": {"f":"PAR-EL.png"},
  "PAR:EN": {"f":"PAR-EN.png"},
  "PAR:ENGI": {"f":"PAR-ENGI.png"},
  "PAR:ERA": {"f":"PAR-ERA.png"},
  "PAR:ERF": {"c":"#784712"},
  "PAR:GFC": {"f":"PAR-GFC.png"},
  "PAR:GLE": {"c":"#840606"},
  "PAR:HO": {"f":"PAR-HO.png"},
  "PAR:KER": {"f":"PAR-KER.png"},
  "PAR:MC": {"f":"PAR-MC.png"},
  "PAR:ML": {"f":"PAR-ML.png"},
  "PAR:OR": {"c":"#624a28"},
  "PAR:ORA": {"c":"#844106"},
  "PAR:PUB": {"f":"PAR-PUB.png"},
  "PAR:RI": {"c":"#064484"},
  "PAR:RMS": {"f":"PAR-RMS.png"},
  "PAR:SAN": {"f":"PAR-SAN.png"},
  "PAR:STLAP": {"f":"PAR-STLAP.png"},
  "PAR:STM": {"f":"PAR-STM.png"},
  "PAR:STMPA": {"f":"PAR-STMPA.png"},
  "PAR:SU": {"c":"#0d7c30"},
  "PAR:TEP": {"f":"PAR-TEP.png"},
  "PAR:TFI": {"f":"PAR-TFI.png"},
  "PAR:TTE": {"c":"#840706"},
  "PAR:URW": {"f":"PAR-URW.png"},
  "PAR:VIE": {"c":"#84060f"},
  "PAR:VIV": {"c":"#6b1e62"},
  "TFSA:AAGEET": {"c":"#7e0c23"},
  "TFSA:AASAET": {"c":"#7e0c23"},
  "TFSA:APACXJ": {"f":"TFSA-APACXJ.png"},
  "TFSA:CARTBL": {"c":"#7e0c23"},
  "TFSA:COGEM": {"f":"TFSA-COGEM.png"},
  "TFSA:COGES": {"f":"TFSA-COGES.png"},
  "TFSA:COGMAN": {"f":"TFSA-COGMAN.png"},
  "TFSA:COGOE": {"f":"TFSA-COGOE.png"},
  "TFSA:COOPTI": {"f":"TFSA-COOPTI.png"},
  "TFSA:CSP500": {"f":"TFSA-CSP500.png"},
  "TFSA:CSPROP": {"f":"TFSA-CSPROP.png"},
  "TFSA:CTOP50": {"f":"TFSA-CTOP50.png"},
  "TFSA:DIVTRX": {"f":"TFSA-DIVTRX.png"},
  "TFSA:EASY5": {"c":"#7e0c23"},
  "TFSA:EASYAI": {"c":"#7e0c23"},
  "TFSA:EASYBF": {"c":"#7e0c23"},
  "TFSA:EASYGE": {"c":"#7e0c23"},
  "TFSA:ETF500": {"f":"TFSA-ETF500.png"},
  "TFSA:ETF5IT": {"f":"TFSA-ETF5IT.png"},
  "TFSA:ETFBND": {"f":"TFSA-ETFBND.png"},
  "TFSA:ETFEMA": {"f":"TFSA-ETFEMA.png"},
  "TFSA:ETFGGB": {"f":"TFSA-ETFGGB.png"},
  "TFSA:ETFGRE": {"f":"TFSA-ETFGRE.png"},
  "TFSA:ETFSAP": {"f":"TFSA-ETFSAP.png"},
  "TFSA:ETFSRI": {"f":"TFSA-ETFSRI.png"},
  "TFSA:ETFSWX": {"f":"TFSA-ETFSWX.png"},
  "TFSA:ETFT40": {"f":"TFSA-ETFT40.png"},
  "TFSA:ETFWLD": {"f":"TFSA-ETFWLD.png"},
  "TFSA:FNBEMG": {"c":"#764d14"},
  "TFSA:FNBINF": {"c":"#764d14"},
  "TFSA:FNBMID": {"c":"#764d14"},
  "TFSA:FNBT40": {"c":"#764d14"},
  "TFSA:GLOBAL": {"f":"TFSA-GLOBAL.png"},
  "TFSA:GLODIV": {"f":"TFSA-GLODIV.png"},
  "TFSA:GLPROP": {"f":"TFSA-GLPROP.png"},
  "TFSA:INCOME": {"f":"TFSA-INCOME.png"},
  "TFSA:PCWGE": {"f":"TFSA-PCWGE.png"},
  "TFSA:RWDVF": {"c":"#813009"},
  "TFSA:RWGPR": {"c":"#813009"},
  "TFSA:RWINC": {"c":"#813009"},
  "TFSA:VUNGLE": {"f":"TFSA-VUNGLE.png"},
  "TFSA:WNXT40": {"f":"TFSA-WNXT40.png"},
  "TFSA:WTOP20": {"f":"TFSA-WTOP20.png"},
  "US:AAAU": {"f":"US-AAAU.png"},
  "US:AAL": {"f":"US-AAL.png"},
  "US:AAPL": {"f":"US-AAPL.png"},
  "US:ABBV": {"f":"US-ABBV.png"},
  "US:ABNB": {"f":"US-ABNB.png"},
  "US:ABT": {"f":"US-ABT.png"},
  "US:ACGL": {"f":"US-ACGL.png"},
  "US:ACHR": {"f":"US-ACHR.png"},
  "US:ACI": {"f":"US-ACI.png"},
  "US:ACM": {"f":"US-ACM.png"},
  "US:ACN": {"f":"US-ACN.png"},
  "US:ACWI": {"f":"US-ACWI.png"},
  "US:ACWX": {"f":"US-ACWX.png"},
  "US:ADBE": {"f":"US-ADBE.png"},
  "US:ADC": {"f":"US-ADC.png"},
  "US:ADI": {"f":"US-ADI.png"},
  "US:ADM": {"f":"US-ADM.png"},
  "US:ADP": {"f":"US-ADP.png"},
  "US:ADSK": {"f":"US-ADSK.png"},
  "US:ADUS": {"f":"US-ADUS.png"},
  "US:AEE": {"f":"US-AEE.png"},
  "US:AEM": {"f":"US-AEM.png"},
  "US:AEO": {"f":"US-AEO.png"},
  "US:AEP": {"f":"US-AEP.png"},
  "US:AES": {"f":"US-AES.png"},
  "US:AFG": {"f":"US-AFG.png"},
  "US:AFL": {"c":"#0b617e"},
  "US:AFRM": {"f":"US-AFRM.png"},
  "US:AG": {"f":"US-AG.png"},
  "US:AGCO": {"f":"US-AGCO.png"},
  "US:AGG": {"f":"US-AGG.png"},
  "US:AGI": {"f":"US-AGI.png"},
  "US:AGNC": {"f":"US-AGNC.png"},
  "US:AI": {"f":"US-AI.png"},
  "US:AIG": {"f":"US-AIG.png"},
  "US:AIRC": {"f":"US-AIRC.png"},
  "US:AIZ": {"f":"US-AIZ.png"},
  "US:AJG": {"f":"US-AJG.png"},
  "US:AKAM": {"f":"US-AKAM.png"},
  "US:ALAB": {"f":"US-ALAB.png"},
  "US:ALB": {"f":"US-ALB.png"},
  "US:ALE": {"f":"US-ALE.png"},
  "US:ALGN": {"f":"US-ALGN.png"},
  "US:ALHC": {"f":"US-ALHC.png"},
  "US:ALL": {"f":"US-ALL.png"},
  "US:ALLE": {"f":"US-ALLE.png"},
  "US:ALLY": {"c":"#741475"},
  "US:ALNY": {"f":"US-ALNY.png"},
  "US:AM": {"f":"US-AM.png"},
  "US:AMAT": {"f":"US-AMAT.png"},
  "US:AMBA": {"f":"US-AMBA.png"},
  "US:AMD": {"f":"US-AMD.png"},
  "US:AME": {"f":"US-AME.png"},
  "US:AMED": {"f":"US-AMED.png"},
  "US:AMGN": {"f":"US-AMGN.png"},
  "US:AMH": {"f":"US-AMH.png"},
  "US:AMLP": {"f":"US-AMLP.png"},
  "US:AMP": {"f":"US-AMP.png"},
  "US:AMR": {"f":"US-AMR.png"},
  "US:AMT": {"f":"US-AMT.png"},
  "US:AMZN": {"f":"US-AMZN.png"},
  "US:ANET": {"f":"US-ANET.png"},
  "US:ANF": {"f":"US-ANF.png"},
  "US:ANGL": {"f":"US-ANGL.png"},
  "US:ANSS": {"f":"US-ANSS.png"},
  "US:AON": {"f":"US-AON.png"},
  "US:AOS": {"c":"#177242"},
  "US:AOSL": {"f":"US-AOSL.png"},
  "US:APA": {"f":"US-APA.png"},
  "US:APD": {"c":"#830725"},
  "US:APH": {"f":"US-APH.png"},
  "US:APLD": {"f":"US-APLD.png"},
  "US:APO": {"f":"US-APO.png"},
  "US:APP": {"f":"US-APP.png"},
  "US:APPF": {"f":"US-APPF.png"},
  "US:APPN": {"f":"US-APPN.png"},
  "US:APTV": {"f":"US-APTV.png"},
  "US:AR": {"f":"US-AR.png"},
  "US:ARCB": {"f":"US-ARCB.png"},
  "US:ARE": {"c":"#284262"},
  "US:ARES": {"f":"US-ARES.png"},
  "US:ARKB": {"f":"US-ARKB.png"},
  "US:ARKF": {"f":"US-ARKF.png"},
  "US:ARKG": {"f":"US-ARKG.png"},
  "US:ARKK": {"f":"US-ARKK.png"},
  "US:ARKQ": {"f":"US-ARKQ.png"},
  "US:ARKW": {"f":"US-ARKW.png"},
  "US:ARLP": {"f":"US-ARLP.png"},
  "US:ARM": {"f":"US-ARM.png"},
  "US:AROC": {"f":"US-AROC.png"},
  "US:ARTNA": {"c":"#246661"},
  "US:ARWR": {"f":"US-ARWR.png"},
  "US:ASAN": {"f":"US-ASAN.png"},
  "US:ASHR": {"f":"US-ASHR.png"},
  "US:ASIX": {"f":"US-ASIX.png"},
  "US:ASML": {"f":"US-ASML.png"},
  "US:ASTH": {"f":"US-ASTH.png"},
  "US:ASTS": {"f":"US-ASTS.png"},
  "US:ATI": {"f":"US-ATI.png"},
  "US:ATO": {"f":"US-ATO.png"},
  "US:AU": {"f":"US-AU.png"},
  "US:AVA": {"f":"US-AVA.png"},
  "US:AVAV": {"f":"US-AVAV.png"},
  "US:AVB": {"f":"US-AVB.png"},
  "US:AVDE": {"f":"US-AVDE.png"},
  "US:AVDV": {"f":"US-AVDV.png"},
  "US:AVEM": {"f":"US-AVEM.png"},
  "US:AVGO": {"f":"US-AVGO.png"},
  "US:AVTR": {"f":"US-AVTR.png"},
  "US:AVUS": {"f":"US-AVUS.png"},
  "US:AVUV": {"f":"US-AVUV.png"},
  "US:AWK": {"f":"US-AWK.png"},
  "US:AWR": {"f":"US-AWR.png"},
  "US:AXON": {"f":"US-AXON.png"},
  "US:AXP": {"f":"US-AXP.png"},
  "US:AYX": {"f":"US-AYX.png"},
  "US:AZEK": {"f":"US-AZEK.png"},
  "US:AZO": {"f":"US-AZO.png"},
  "US:BA": {"f":"US-BA.png"},
  "US:BABA": {"f":"US-BABA.png"},
  "US:BAC": {"f":"US-BAC.png"},
  "US:BAH": {"f":"US-BAH.png"},
  "US:BAL": {"f":"US-BAL.png"},
  "US:BAND": {"f":"US-BAND.png"},
  "US:BAR": {"f":"US-BAR.png"},
  "US:BAX": {"f":"US-BAX.png"},
  "US:BBAI": {"f":"US-BBAI.png"},
  "US:BBEU": {"f":"US-BBEU.png"},
  "US:BBJP": {"f":"US-BBJP.png"},
  "US:BBWI": {"f":"US-BBWI.png"},
  "US:BBY": {"f":"US-BBY.png"},
  "US:BDN": {"f":"US-BDN.png"},
  "US:BDX": {"f":"US-BDX.png"},
  "US:BE": {"f":"US-BE.png"},
  "US:BEAM": {"c":"#827407"},
  "US:BEN": {"f":"US-BEN.png"},
  "US:BF-B": {"f":"US-BF-B.png"},
  "US:BHP": {"f":"US-BHP.png"},
  "US:BIDU": {"f":"US-BIDU.png"},
  "US:BIG": {"f":"US-BIG.png"},
  "US:BIIB": {"c":"#204969"},
  "US:BIL": {"f":"US-BIL.png"},
  "US:BILL": {"f":"US-BILL.png"},
  "US:BIRK": {"f":"US-BIRK.png"},
  "US:BITB": {"f":"US-BITB.png"},
  "US:BITF": {"f":"US-BITF.png"},
  "US:BITI": {"f":"US-BITI.png"},
  "US:BITO": {"f":"US-BITO.png"},
  "US:BITS": {"f":"US-BITS.png"},
  "US:BITX": {"f":"US-BITX.png"},
  "US:BIV": {"f":"US-BIV.png"},
  "US:BK": {"f":"US-BK.png"},
  "US:BKCH": {"c":"#813209"},
  "US:BKH": {"f":"US-BKH.png"},
  "US:BKLN": {"f":"US-BKLN.png"},
  "US:BKNG": {"f":"US-BKNG.png"},
  "US:BKR": {"f":"US-BKR.png"},
  "US:BLD": {"f":"US-BLD.png"},
  "US:BLDR": {"c":"#6f1b22"},
  "US:BLK": {"f":"US-BLK.png"},
  "US:BLMN": {"f":"US-BLMN.png"},
  "US:BLOK": {"f":"US-BLOK.png"},
  "US:BLV": {"f":"US-BLV.png"},
  "US:BMBL": {"f":"US-BMBL.png"},
  "US:BMNR": {"f":"US-BMNR.png"},
  "US:BMY": {"f":"US-BMY.png"},
  "US:BND": {"f":"US-BND.png"},
  "US:BNDX": {"f":"US-BNDX.png"},
  "US:BNO": {"f":"US-BNO.png"},
  "US:BNTX": {"f":"US-BNTX.png"},
  "US:BOIL": {"f":"US-BOIL.png"},
  "US:BOX": {"f":"US-BOX.png"},
  "US:BRK-A": {"f":"US-BRK-A.png"},
  "US:BRK-B": {"f":"US-BRK-B.png"},
  "US:BRO": {"f":"US-BRO.png"},
  "US:BRZE": {"f":"US-BRZE.png"},
  "US:BSCP": {"f":"US-BSCP.png"},
  "US:BSCQ": {"f":"US-BSCQ.png"},
  "US:BSJO": {"f":"US-BSJO.png"},
  "US:BSJP": {"f":"US-BSJP.png"},
  "US:BSV": {"f":"US-BSV.png"},
  "US:BSX": {"f":"US-BSX.png"},
  "US:BSY": {"f":"US-BSY.png"},
  "US:BTC": {"f":"US-BTC.png"},
  "US:BTCW": {"f":"US-BTCW.png"},
  "US:BTG": {"f":"US-BTG.png"},
  "US:BTU": {"f":"US-BTU.png"},
  "US:BUD": {"f":"US-BUD.png"},
  "US:BUG": {"f":"US-BUG.png"},
  "US:BULL": {"f":"US-BULL.png"},
  "US:BURL": {"f":"US-BURL.png"},
  "US:BWX": {"f":"US-BWX.png"},
  "US:BWXT": {"c":"#62282c"},
  "US:BX": {"f":"US-BX.png"},
  "US:BXP": {"f":"US-BXP.png"},
  "US:BYND": {"f":"US-BYND.png"},
  "US:C": {"f":"US-C.png"},
  "US:CACI": {"f":"US-CACI.png"},
  "US:CAE": {"f":"US-CAE.png"},
  "US:CAG": {"f":"US-CAG.png"},
  "US:CAH": {"f":"US-CAH.png"},
  "US:CAKE": {"f":"US-CAKE.png"},
  "US:CANE": {"f":"US-CANE.png"},
  "US:CARG": {"f":"US-CARG.png"},
  "US:CARR": {"f":"US-CARR.png"},
  "US:CART": {"f":"US-CART.png"},
  "US:CASY": {"f":"US-CASY.png"},
  "US:CAT": {"f":"US-CAT.png"},
  "US:CB": {"f":"US-CB.png"},
  "US:CBOE": {"f":"US-CBOE.png"},
  "US:CC": {"f":"US-CC.png"},
  "US:CCI": {"f":"US-CCI.png"},
  "US:CCJ": {"f":"US-CCJ.png"},
  "US:CCL": {"f":"US-CCL.png"},
  "US:CDE": {"c":"#723d18"},
  "US:CDNA": {"f":"US-CDNA.png"},
  "US:CDNS": {"c":"#711822"},
  "US:CDW": {"f":"US-CDW.png"},
  "US:CE": {"f":"US-CE.png"},
  "US:CEG": {"f":"US-CEG.png"},
  "US:CELH": {"f":"US-CELH.png"},
  "US:CENT": {"c":"#28624b"},
  "US:CERT": {"f":"US-CERT.png"},
  "US:CEVA": {"f":"US-CEVA.png"},
  "US:CF": {"f":"US-CF.png"},
  "US:CFG": {"f":"US-CFG.png"},
  "US:CFLT": {"f":"US-CFLT.png"},
  "US:CG": {"f":"US-CG.png"},
  "US:CHD": {"c":"#7a102b"},
  "US:CHE": {"c":"#226167"},
  "US:CHEF": {"c":"#6b1f27"},
  "US:CHK": {"f":"US-CHK.png"},
  "US:CHRW": {"f":"US-CHRW.png"},
  "US:CHTR": {"f":"US-CHTR.png"},
  "US:CHWY": {"f":"US-CHWY.png"},
  "US:CHX": {"c":"#285362"},
  "US:CI": {"f":"US-CI.png"},
  "US:CIBR": {"f":"US-CIBR.png"},
  "US:CIEN": {"f":"US-CIEN.png"},
  "US:CIFR": {"f":"US-CIFR.png"},
  "US:CINF": {"f":"US-CINF.png"},
  "US:CIVI": {"f":"US-CIVI.png"},
  "US:CL": {"f":"US-CL.png"},
  "US:CLF": {"f":"US-CLF.png"},
  "US:CLSK": {"f":"US-CLSK.png"},
  "US:CLX": {"f":"US-CLX.png"},
  "US:CMC": {"f":"US-CMC.png"},
  "US:CMCSA": {"f":"US-CMCSA.png"},
  "US:CME": {"c":"#125a78"},
  "US:CMG": {"c":"#741815"},
  "US:CMI": {"f":"US-CMI.png"},
  "US:CMS": {"f":"US-CMS.png"},
  "US:CNC": {"c":"#174d73"},
  "US:CNP": {"c":"#135776"},
  "US:COF": {"f":"US-COF.png"},
  "US:COIN": {"f":"US-COIN.png"},
  "US:COP": {"f":"US-COP.png"},
  "US:COPX": {"f":"US-COPX.png"},
  "US:COR": {"f":"US-COR.png"},
  "US:CORN": {"c":"#526228"},
  "US:COST": {"f":"US-COST.png"},
  "US:COTY": {"f":"US-COTY.png"},
  "US:COWZ": {"f":"US-COWZ.png"},
  "US:CPB": {"f":"US-CPB.png"},
  "US:CPER": {"f":"US-CPER.png"},
  "US:CPK": {"c":"#283662"},
  "US:CPRI": {"f":"US-CPRI.png"},
  "US:CPRT": {"f":"US-CPRT.png"},
  "US:CPT": {"f":"US-CPT.png"},
  "US:CQP": {"f":"US-CQP.png"},
  "US:CQQQ": {"f":"US-CQQQ.png"},
  "US:CR": {"f":"US-CR.png"},
  "US:CRDO": {"f":"US-CRDO.png"},
  "US:CRGY": {"f":"US-CRGY.png"},
  "US:CRL": {"f":"US-CRL.png"},
  "US:CRM": {"f":"US-CRM.png"},
  "US:CROX": {"f":"US-CROX.png"},
  "US:CRS": {"c":"#781229"},
  "US:CRSP": {"f":"US-CRSP.png"},
  "US:CRUS": {"f":"US-CRUS.png"},
  "US:CRWD": {"f":"US-CRWD.png"},
  "US:CSCO": {"f":"US-CSCO.png"},
  "US:CSWI": {"c":"#3d6228"},
  "US:CSX": {"f":"US-CSX.png"},
  "US:CTAS": {"c":"#123078"},
  "US:CTRA": {"f":"US-CTRA.png"},
  "US:CTRE": {"f":"US-CTRE.png"},
  "US:CTSH": {"f":"US-CTSH.png"},
  "US:CTVA": {"f":"US-CTVA.png"},
  "US:CUBE": {"f":"US-CUBE.png"},
  "US:CURI": {"f":"US-CURI.png"},
  "US:CUZ": {"f":"US-CUZ.png"},
  "US:CVNA": {"f":"US-CVNA.png"},
  "US:CVS": {"f":"US-CVS.png"},
  "US:CVX": {"f":"US-CVX.png"},
  "US:CW": {"f":"US-CW.png"},
  "US:CWT": {"f":"US-CWT.png"},
  "US:CYBR": {"f":"US-CYBR.png"},
  "US:CYTK": {"f":"US-CYTK.png"},
  "US:D": {"f":"US-D.png"},
  "US:DAL": {"f":"US-DAL.png"},
  "US:DAPP": {"f":"US-DAPP.png"},
  "US:DASH": {"f":"US-DASH.png"},
  "US:DBA": {"c":"#7f2c0b"},
  "US:DBB": {"f":"US-DBB.png"},
  "US:DBC": {"f":"US-DBC.png"},
  "US:DBE": {"f":"US-DBE.png"},
  "US:DBO": {"f":"US-DBO.png"},
  "US:DBX": {"c":"#655d24"},
  "US:DD": {"f":"US-DD.png"},
  "US:DDOG": {"f":"US-DDOG.png"},
  "US:DDS": {"f":"US-DDS.png"},
  "US:DE": {"f":"US-DE.png"},
  "US:DECK": {"f":"US-DECK.png"},
  "US:DEFI": {"f":"US-DEFI.png"},
  "US:DEI": {"f":"US-DEI.png"},
  "US:DELL": {"f":"US-DELL.png"},
  "US:DEM": {"f":"US-DEM.png"},
  "US:DEO": {"f":"US-DEO.png"},
  "US:DES": {"f":"US-DES.png"},
  "US:DFAC": {"f":"US-DFAC.png"},
  "US:DFAE": {"f":"US-DFAE.png"},
  "US:DFAI": {"f":"US-DFAI.png"},
  "US:DFAU": {"f":"US-DFAU.png"},
  "US:DFAX": {"f":"US-DFAX.png"},
  "US:DFIV": {"f":"US-DFIV.png"},
  "US:DFS": {"c":"#763913"},
  "US:DFUS": {"f":"US-DFUS.png"},
  "US:DG": {"f":"US-DG.png"},
  "US:DGRO": {"f":"US-DGRO.png"},
  "US:DGRW": {"f":"US-DGRW.png"},
  "US:DGS": {"f":"US-DGS.png"},
  "US:DGX": {"c":"#4a6228"},
  "US:DH": {"f":"US-DH.png"},
  "US:DHI": {"f":"US-DHI.png"},
  "US:DHR": {"f":"US-DHR.png"},
  "US:DIA": {"f":"US-SPY.png"},
  "US:DINO": {"f":"US-DINO.png"},
  "US:DIOD": {"c":"#254964"},
  "US:DIS": {"f":"US-DIS.png"},
  "US:DJP": {"f":"US-DJP.png"},
  "US:DKL": {"c":"#771319"},
  "US:DKNG": {"f":"US-DKNG.png"},
  "US:DLR": {"f":"US-DLR.png"},
  "US:DLS": {"f":"US-DLS.png"},
  "US:DLTR": {"c":"#396525"},
  "US:DNN": {"f":"US-DNN.png"},
  "US:DNUT": {"f":"US-DNUT.png"},
  "US:DOC": {"f":"US-DOC.png"},
  "US:DOCN": {"f":"US-DOCN.png"},
  "US:DOCS": {"f":"US-DOCS.png"},
  "US:DOCU": {"f":"US-DOCU.png"},
  "US:DON": {"f":"US-DON.png"},
  "US:DOV": {"c":"#184872"},
  "US:DOW": {"f":"US-DOW.png"},
  "US:DPZ": {"f":"US-DPZ.png"},
  "US:DRD": {"f":"US-DRD.png"},
  "US:DRI": {"c":"#632827"},
  "US:DRS": {"f":"US-DRS.png"},
  "US:DTE": {"f":"US-DTE.png"},
  "US:DTM": {"f":"US-DTM.png"},
  "US:DUK": {"f":"US-DUK.png"},
  "US:DUOL": {"f":"US-DUOL.png"},
  "US:DVA": {"f":"US-DVA.png"},
  "US:DVAX": {"f":"US-DVAX.png"},
  "US:DVN": {"f":"US-DVN.png"},
  "US:DVY": {"f":"US-DVY.png"},
  "US:DXC": {"f":"US-DXC.png"},
  "US:DXCM": {"f":"US-DXCM.png"},
  "US:DXJ": {"f":"US-DXJ.png"},
  "US:DY": {"f":"US-DY.png"},
  "US:EA": {"f":"US-EA.png"},
  "US:EAT": {"f":"US-EAT.png"},
  "US:EBAY": {"f":"US-EBAY.png"},
  "US:EBND": {"f":"US-EBND.png"},
  "US:ECL": {"f":"US-ECL.png"},
  "US:ED": {"f":"US-ED.png"},
  "US:EEM": {"f":"US-EEM.png"},
  "US:EEMV": {"f":"US-EEMV.png"},
  "US:EFA": {"f":"US-EFA.png"},
  "US:EFX": {"f":"US-EFX.png"},
  "US:EG": {"f":"US-EG.png"},
  "US:EGP": {"f":"US-EGP.png"},
  "US:EL": {"f":"US-EL.png"},
  "US:ELF": {"f":"US-ELF.png"},
  "US:ELS": {"f":"US-ELS.png"},
  "US:ELV": {"f":"US-ELV.png"},
  "US:EMB": {"f":"US-EMB.png"},
  "US:EME": {"f":"US-EME.png"},
  "US:EMHY": {"f":"US-EMHY.png"},
  "US:EMLC": {"f":"US-EMLC.png"},
  "US:EMN": {"f":"US-EMN.png"},
  "US:EMR": {"c":"#1a486f"},
  "US:ENB": {"f":"US-ENB.png"},
  "US:ENPH": {"f":"US-ENPH.png"},
  "US:ENR": {"f":"US-ENR.png"},
  "US:ENSG": {"f":"US-ENSG.png"},
  "US:ENTG": {"f":"US-ENTG.png"},
  "US:ENV": {"c":"#1f4e6a"},
  "US:ENVA": {"f":"US-ENVA.png"},
  "US:EOG": {"f":"US-EOG.png"},
  "US:EPAM": {"f":"US-EPAM.png"},
  "US:EPC": {"c":"#067184"},
  "US:EPD": {"f":"US-EPD.png"},
  "US:EPRT": {"f":"US-EPRT.png"},
  "US:EQIX": {"c":"#7f0b10"},
  "US:EQR": {"f":"US-EQR.png"},
  "US:EQT": {"f":"US-EQT.png"},
  "US:EQX": {"c":"#624b28"},
  "US:ERIE": {"f":"US-ERIE.png"},
  "US:ES": {"c":"#068434"},
  "US:ESRT": {"c":"#496228"},
  "US:ESS": {"f":"US-ESS.png"},
  "US:ESTC": {"f":"US-ESTC.png"},
  "US:ET": {"f":"US-ET.png"},
  "US:ETHA": {"f":"US-ETHA.png"},
  "US:ETHE": {"f":"US-ETHE.png"},
  "US:ETHW": {"f":"US-ETHW.png"},
  "US:ETN": {"f":"US-ETN.png"},
  "US:ETR": {"f":"US-ETR.png"},
  "US:ETSY": {"f":"US-ETSY.png"},
  "US:EVH": {"f":"US-EVH.png"},
  "US:EVR": {"c":"#192570"},
  "US:EVRG": {"f":"US-EVRG.png"},
  "US:EW": {"f":"US-EW.png"},
  "US:EWA": {"f":"US-EWA.png"},
  "US:EWC": {"f":"US-EWC.png"},
  "US:EWD": {"f":"US-EWD.png"},
  "US:EWG": {"f":"US-EWG.png"},
  "US:EWH": {"f":"US-EWH.png"},
  "US:EWI": {"f":"US-EWI.png"},
  "US:EWJ": {"f":"US-EWJ.png"},
  "US:EWL": {"f":"US-EWL.png"},
  "US:EWN": {"f":"US-EWN.png"},
  "US:EWP": {"f":"US-EWP.png"},
  "US:EWQ": {"f":"US-EWQ.png"},
  "US:EWS": {"f":"US-EWS.png"},
  "US:EWT": {"f":"US-EWT.png"},
  "US:EWU": {"f":"US-EWU.png"},
  "US:EWW": {"f":"US-EWW.png"},
  "US:EWY": {"f":"US-EWY.png"},
  "US:EWZ": {"f":"US-EWZ.png"},
  "US:EXAS": {"f":"US-EXAS.png"},
  "US:EXC": {"f":"US-EXC.png"},
  "US:EXK": {"c":"#622835"},
  "US:EXP": {"f":"US-EXP.png"},
  "US:EXPE": {"f":"US-EXPE.png"},
  "US:EXR": {"c":"#147542"},
  "US:EZU": {"f":"US-EZU.png"},
  "US:F": {"f":"US-F.png"},
  "US:FALN": {"f":"US-FALN.png"},
  "US:FANG": {"f":"US-FANG.png"},
  "US:FAST": {"f":"US-FAST.png"},
  "US:FBIN": {"f":"US-FBIN.png"},
  "US:FBND": {"f":"US-FBND.png"},
  "US:FBTC": {"f":"US-FBTC.png"},
  "US:FCNCA": {"f":"US-FCNCA.png"},
  "US:FCPT": {"f":"US-FCPT.png"},
  "US:FCX": {"f":"US-FCX.png"},
  "US:FDN": {"f":"US-FDN.png"},
  "US:FDS": {"f":"US-FDS.png"},
  "US:FDX": {"f":"US-FDX.png"},
  "US:FE": {"f":"US-FE.png"},
  "US:FFIV": {"f":"US-FFIV.png"},
  "US:FI": {"f":"US-FI.png"},
  "US:FICO": {"f":"US-FICO.png"},
  "US:FIGS": {"f":"US-FIGS.png"},
  "US:FINX": {"f":"US-FINX.png"},
  "US:FIS": {"f":"US-FIS.png"},
  "US:FITB": {"f":"US-FITB.png"},
  "US:FIVE": {"f":"US-FIVE.png"},
  "US:FIX": {"f":"US-FIX.png"},
  "US:FLGT": {"f":"US-FLGT.png"},
  "US:FLO": {"f":"US-FLO.png"},
  "US:FLOT": {"f":"US-FLOT.png"},
  "US:FLRN": {"f":"US-FLRN.png"},
  "US:FLS": {"f":"US-FLS.png"},
  "US:FMC": {"f":"US-FMC.png"},
  "US:FNDA": {"f":"US-FNDA.png"},
  "US:FNDB": {"f":"US-FNDB.png"},
  "US:FNDC": {"f":"US-FNDC.png"},
  "US:FNDE": {"f":"US-FNDE.png"},
  "US:FNDF": {"f":"US-FNDF.png"},
  "US:FNV": {"f":"US-FNV.png"},
  "US:FORM": {"f":"US-FORM.png"},
  "US:FOX": {"f":"US-FOX.png"},
  "US:FOXA": {"f":"US-FOXA.png"},
  "US:FR": {"f":"US-FR.png"},
  "US:FROG": {"f":"US-FROG.png"},
  "US:FRPT": {"c":"#4c6228"},
  "US:FRSH": {"f":"US-FRSH.png"},
  "US:FSLR": {"f":"US-FSLR.png"},
  "US:FTGC": {"f":"US-FTGC.png"},
  "US:FTNT": {"f":"US-FTNT.png"},
  "US:FTV": {"f":"US-FTV.png"},
  "US:FUBO": {"f":"US-FUBO.png"},
  "US:FUL": {"f":"US-FUL.png"},
  "US:FUN": {"f":"US-FUN.png"},
  "US:FXI": {"f":"US-FXI.png"},
  "US:GATO": {"f":"US-GATO.png"},
  "US:GBTC": {"f":"US-GBTC.png"},
  "US:GBX": {"f":"US-GBX.png"},
  "US:GCC": {"f":"US-GCC.png"},
  "US:GD": {"f":"US-GD.png"},
  "US:GDDY": {"f":"US-GDDY.png"},
  "US:GDX": {"f":"US-GDX.png"},
  "US:GDXJ": {"f":"US-GDXJ.png"},
  "US:GE": {"c":"#060684"},
  "US:GEHC": {"c":"#400980"},
  "US:GEN": {"f":"US-GEN.png"},
  "US:GENI": {"f":"US-GENI.png"},
  "US:GEV": {"c":"#0f787a"},
  "US:GFS": {"f":"US-GFS.png"},
  "US:GGB": {"f":"US-GGB.png"},
  "US:GGG": {"f":"US-GGG.png"},
  "US:GH": {"f":"US-GH.png"},
  "US:GILD": {"f":"US-GILD.png"},
  "US:GIS": {"f":"US-GIS.png"},
  "US:GLBE": {"c":"#812609"},
  "US:GLD": {"f":"US-SPY.png"},
  "US:GLDM": {"f":"US-GLDM.png"},
  "US:GLOB": {"f":"US-GLOB.png"},
  "US:GLP": {"c":"#840619"},
  "US:GLW": {"f":"US-GLW.png"},
  "US:GM": {"f":"US-GM.png"},
  "US:GME": {"f":"US-GME.png"},
  "US:GMRE": {"c":"#286259"},
  "US:GOLD": {"f":"US-GOLD.png"},
  "US:GOOG": {"f":"US-GOOG.png"},
  "US:GOOGL": {"f":"US-GOOGL.png"},
  "US:GOOS": {"c":"#062484"},
  "US:GOVT": {"f":"US-GOVT.png"},
  "US:GPC": {"f":"US-GPC.png"},
  "US:GPN": {"c":"#134777"},
  "US:GPOR": {"c":"#234167"},
  "US:GPS": {"f":"US-GPS.png"},
  "US:GRAB": {"f":"US-GRAB.png"},
  "US:GRMN": {"f":"US-GRMN.png"},
  "US:GS": {"f":"US-GS.png"},
  "US:GSG": {"f":"US-GSG.png"},
  "US:GSHD": {"f":"US-GSHD.png"},
  "US:GSY": {"f":"US-GSY.png"},
  "US:GTLB": {"f":"US-GTLB.png"},
  "US:GTLS": {"f":"US-GTLS.png"},
  "US:GTY": {"f":"US-GTY.png"},
  "US:GVA": {"f":"US-GVA.png"},
  "US:GVI": {"f":"US-GVI.png"},
  "US:GWW": {"f":"US-GWW.png"},
  "US:GWX": {"f":"US-GWX.png"},
  "US:HACK": {"f":"US-HACK.png"},
  "US:HAIN": {"c":"#7c610e"},
  "US:HAL": {"f":"US-HAL.png"},
  "US:HALO": {"f":"US-HALO.png"},
  "US:HAS": {"f":"US-HAS.png"},
  "US:HASI": {"f":"US-HASI.png"},
  "US:HAYN": {"c":"#682230"},
  "US:HBAN": {"f":"US-HBAN.png"},
  "US:HBI": {"c":"#741b16"},
  "US:HCA": {"c":"#223668"},
  "US:HCC": {"f":"US-HCC.png"},
  "US:HD": {"f":"US-HD.png"},
  "US:HEDJ": {"f":"US-HEDJ.png"},
  "US:HEI": {"f":"US-HEI.png"},
  "US:HES": {"f":"US-HES.png"},
  "US:HESM": {"f":"US-HESM.png"},
  "US:HII": {"f":"US-HII.png"},
  "US:HIMS": {"f":"US-HIMS.png"},
  "US:HIW": {"f":"US-HIW.png"},
  "US:HL": {"f":"US-HL.png"},
  "US:HLT": {"f":"US-HLT.png"},
  "US:HMY": {"c":"#7f0b0d"},
  "US:HODL": {"f":"US-HODL.png"},
  "US:HOLX": {"f":"US-HOLX.png"},
  "US:HON": {"f":"US-HON.png"},
  "US:HOOD": {"f":"US-HOOD.png"},
  "US:HP": {"f":"US-HP.png"},
  "US:HPE": {"f":"US-HPE.png"},
  "US:HPP": {"c":"#284862"},
  "US:HPQ": {"f":"US-HPQ.png"},
  "US:HRL": {"f":"US-HRL.png"},
  "US:HST": {"f":"US-HST.png"},
  "US:HSY": {"f":"US-HSY.png"},
  "US:HUBS": {"f":"US-HUBS.png"},
  "US:HUM": {"f":"US-HUM.png"},
  "US:HUN": {"f":"US-HUN.png"},
  "US:HWM": {"f":"US-HWM.png"},
  "US:HXL": {"c":"#214668"},
  "US:HYG": {"f":"US-HYG.png"},
  "US:HYLB": {"f":"US-HYLB.png"},
  "US:IAG": {"f":"US-IAG.png"},
  "US:IAI": {"f":"US-IAI.png"},
  "US:IAU": {"f":"US-IAU.png"},
  "US:IAUM": {"f":"US-IAUM.png"},
  "US:IBB": {"f":"US-IBB.png"},
  "US:IBDR": {"f":"US-IBDR.png"},
  "US:IBDS": {"f":"US-IBDS.png"},
  "US:IBDT": {"f":"US-IBDT.png"},
  "US:IBIT": {"f":"US-IBIT.png"},
  "US:IBLC": {"f":"US-IBLC.png"},
  "US:IBM": {"f":"US-IBM.png"},
  "US:IBP": {"f":"US-IBP.png"},
  "US:ICE": {"f":"US-ICE.png"},
  "US:ICL": {"c":"#244165"},
  "US:ICSH": {"f":"US-ICSH.png"},
  "US:IDA": {"f":"US-IDA.png"},
  "US:IDV": {"f":"US-IDV.png"},
  "US:IDXX": {"f":"US-IDXX.png"},
  "US:IEF": {"f":"US-IEF.png"},
  "US:IEFA": {"f":"US-IEFA.png"},
  "US:IEI": {"f":"US-IEI.png"},
  "US:IEMG": {"f":"US-IEMG.png"},
  "US:IEUR": {"f":"US-IEUR.png"},
  "US:IEX": {"c":"#0c4e7d"},
  "US:IFF": {"c":"#0b4c7f"},
  "US:IGIB": {"f":"US-IGIB.png"},
  "US:IGLB": {"f":"US-IGLB.png"},
  "US:IGSB": {"f":"US-IGSB.png"},
  "US:IGV": {"f":"US-IGV.png"},
  "US:IHI": {"f":"US-IHI.png"},
  "US:IJH": {"f":"US-IJH.png"},
  "US:IJJ": {"f":"US-IJJ.png"},
  "US:IJK": {"f":"US-IJK.png"},
  "US:IJR": {"f":"US-IJR.png"},
  "US:IJS": {"f":"US-IJS.png"},
  "US:IJT": {"f":"US-IJT.png"},
  "US:ILTB": {"f":"US-ILTB.png"},
  "US:IMTB": {"f":"US-IMTB.png"},
  "US:INDA": {"f":"US-INDA.png"},
  "US:INDI": {"f":"US-INDI.png"},
  "US:INFA": {"f":"US-INFA.png"},
  "US:INFY": {"c":"#114a79"},
  "US:INOD": {"f":"US-INOD.png"},
  "US:INSM": {"c":"#352862"},
  "US:INSP": {"c":"#232268"},
  "US:INTA": {"f":"US-INTA.png"},
  "US:INTC": {"f":"US-INTC.png"},
  "US:INTU": {"f":"US-INTU.png"},
  "US:INVH": {"f":"US-INVH.png"},
  "US:IONQ": {"f":"US-IONQ.png"},
  "US:IPAC": {"f":"US-IPAC.png"},
  "US:IPG": {"f":"US-IPG.png"},
  "US:IQ": {"f":"US-IQ.png"},
  "US:IQV": {"f":"US-IQV.png"},
  "US:IR": {"f":"US-IR.png"},
  "US:IREN": {"f":"US-IREN.png"},
  "US:IRM": {"f":"US-IRM.png"},
  "US:ISRG": {"f":"US-ISRG.png"},
  "US:ISTB": {"f":"US-ISTB.png"},
  "US:IT": {"f":"US-IT.png"},
  "US:ITA": {"f":"US-ITA.png"},
  "US:ITOT": {"f":"US-ITOT.png"},
  "US:ITT": {"f":"US-ITT.png"},
  "US:ITW": {"f":"US-ITW.png"},
  "US:IVV": {"f":"US-IVV.png"},
  "US:IVZ": {"f":"US-IVZ.png"},
  "US:IWB": {"f":"US-IWB.png"},
  "US:IWD": {"f":"US-IWD.png"},
  "US:IWF": {"f":"US-IWF.png"},
  "US:IWM": {"f":"US-IWM.png"},
  "US:IWN": {"f":"US-IWN.png"},
  "US:IWO": {"f":"US-IWO.png"},
  "US:IWP": {"f":"US-IWP.png"},
  "US:IWS": {"f":"US-IWS.png"},
  "US:IWV": {"f":"US-IWV.png"},
  "US:IXUS": {"f":"US-IXUS.png"},
  "US:IYR": {"f":"US-IYR.png"},
  "US:J": {"f":"US-J.png"},
  "US:JACK": {"f":"US-JACK.png"},
  "US:JBGS": {"f":"US-JBGS.png"},
  "US:JCI": {"f":"US-JCI.png"},
  "US:JD": {"f":"US-JD.png"},
  "US:JEF": {"f":"US-JEF.png"},
  "US:JEPI": {"f":"US-JEPI.png"},
  "US:JEPQ": {"f":"US-JEPQ.png"},
  "US:JETS": {"f":"US-JETS.png"},
  "US:JNJ": {"f":"US-JNJ.png"},
  "US:JNK": {"f":"US-JNK.png"},
  "US:JNPR": {"c":"#17735d"},
  "US:JO": {"f":"US-JO.png"},
  "US:JOBY": {"f":"US-JOBY.png"},
  "US:JPM": {"f":"US-JPM.png"},
  "US:JPST": {"f":"US-JPST.png"},
  "US:JWN": {"f":"US-JWN.png"},
  "US:K": {"f":"US-K.png"},
  "US:KBE": {"f":"US-KBE.png"},
  "US:KDP": {"f":"US-KDP.png"},
  "US:KEY": {"f":"US-KEY.png"},
  "US:KEYS": {"f":"US-KEYS.png"},
  "US:KGC": {"f":"US-KGC.png"},
  "US:KGS": {"f":"US-KGS.png"},
  "US:KHC": {"f":"US-KHC.png"},
  "US:KIE": {"c":"#3e6228"},
  "US:KKR": {"f":"US-KKR.png"},
  "US:KLAC": {"f":"US-KLAC.png"},
  "US:KMB": {"f":"US-KMB.png"},
  "US:KMI": {"c":"#802509"},
  "US:KMPR": {"f":"US-KMPR.png"},
  "US:KNX": {"f":"US-KNX.png"},
  "US:KO": {"f":"US-KO.png"},
  "US:KOLD": {"f":"US-KOLD.png"},
  "US:KOPN": {"f":"US-KOPN.png"},
  "US:KR": {"f":"US-KR.png"},
  "US:KRC": {"f":"US-KRC.png"},
  "US:KRE": {"f":"US-KRE.png"},
  "US:KRO": {"f":"US-KRO.png"},
  "US:KSS": {"f":"US-KSS.png"},
  "US:KTOS": {"f":"US-KTOS.png"},
  "US:KVUE": {"f":"US-KVUE.png"},
  "US:KVYO": {"f":"US-KVYO.png"},
  "US:KWEB": {"f":"US-KWEB.png"},
  "US:LAC": {"f":"US-LAC.png"},
  "US:LANC": {"f":"US-LANC.png"},
  "US:LASR": {"f":"US-LASR.png"},
  "US:LBRT": {"c":"#771317"},
  "US:LCID": {"f":"US-LCID.png"},
  "US:LDOS": {"f":"US-LDOS.png"},
  "US:LEMB": {"f":"US-LEMB.png"},
  "US:LEN": {"c":"#254865"},
  "US:LEU": {"c":"#224a68"},
  "US:LEVI": {"f":"US-LEVI.png"},
  "US:LH": {"f":"US-LH.png"},
  "US:LHX": {"c":"#7f0b0f"},
  "US:LI": {"f":"US-LI.png"},
  "US:LII": {"f":"US-LII.png"},
  "US:LIN": {"f":"US-LIN.png"},
  "US:LIT": {"f":"US-LIT.png"},
  "US:LITE": {"c":"#774813"},
  "US:LKQ": {"f":"US-LKQ.png"},
  "US:LLY": {"f":"US-LLY.png"},
  "US:LMND": {"f":"US-LMND.png"},
  "US:LMT": {"f":"US-LMT.png"},
  "US:LNG": {"f":"US-LNG.png"},
  "US:LNT": {"f":"US-LNT.png"},
  "US:LNTH": {"f":"US-LNTH.png"},
  "US:LOW": {"f":"US-LOW.png"},
  "US:LQD": {"f":"US-LQD.png"},
  "US:LRCX": {"f":"US-LRCX.png"},
  "US:LSCC": {"f":"US-LSCC.png"},
  "US:LSI": {"f":"US-LSI.png"},
  "US:LSTR": {"f":"US-LSTR.png"},
  "US:LTC": {"c":"#0f367b"},
  "US:LULU": {"f":"US-LULU.png"},
  "US:LUNR": {"f":"US-LUNR.png"},
  "US:LUV": {"f":"US-LUV.png"},
  "US:LVS": {"f":"US-LVS.png"},
  "US:LYB": {"f":"US-LYB.png"},
  "US:LYV": {"f":"US-LYV.png"},
  "US:M": {"f":"US-M.png"},
  "US:MA": {"f":"US-MA.png"},
  "US:MAA": {"f":"US-MAA.png"},
  "US:MAGS": {"f":"US-MAGS.png"},
  "US:MAR": {"f":"US-MAR.png"},
  "US:MARA": {"f":"US-MARA.png"},
  "US:MAS": {"c":"#244c66"},
  "US:MAT": {"f":"US-MAT.png"},
  "US:MATX": {"f":"US-MATX.png"},
  "US:MBB": {"f":"US-MBB.png"},
  "US:MBLY": {"f":"US-MBLY.png"},
  "US:MC": {"f":"US-MC.png"},
  "US:MCD": {"f":"US-MCD.png"},
  "US:MCHI": {"f":"US-MCHI.png"},
  "US:MCHP": {"f":"US-MCHP.png"},
  "US:MCK": {"f":"US-MCK.png"},
  "US:MCO": {"f":"US-MCO.png"},
  "US:MDB": {"f":"US-MDB.png"},
  "US:MDLZ": {"f":"US-MDLZ.png"},
  "US:MDT": {"f":"US-MDT.png"},
  "US:MELI": {"f":"US-MELI.png"},
  "US:MET": {"f":"US-MET.png"},
  "US:META": {"f":"US-META.png"},
  "US:METC": {"f":"US-METC.png"},
  "US:MGEE": {"c":"#286252"},
  "US:MGK": {"f":"US-MGK.png"},
  "US:MGM": {"f":"US-MGM.png"},
  "US:MGV": {"f":"US-MGV.png"},
  "US:MINT": {"f":"US-MINT.png"},
  "US:MKC": {"f":"US-MKC.png"},
  "US:MKL": {"f":"US-MKL.png"},
  "US:MKTX": {"f":"US-MKTX.png"},
  "US:MLM": {"f":"US-MLM.png"},
  "US:MMC": {"f":"US-MMC.png"},
  "US:MMM": {"f":"US-MMM.png"},
  "US:MNDY": {"f":"US-MNDY.png"},
  "US:MNST": {"f":"US-MNST.png"},
  "US:MO": {"f":"US-MO.png"},
  "US:MODG": {"f":"US-MODG.png"},
  "US:MOG-A": {"f":"US-MOG-A.png"},
  "US:MOH": {"f":"US-MOH.png"},
  "US:MORN": {"c":"#840606"},
  "US:MOS": {"c":"#6f641b"},
  "US:MP": {"f":"US-MP.png"},
  "US:MPC": {"f":"US-MPC.png"},
  "US:MPLX": {"f":"US-MPLX.png"},
  "US:MPW": {"f":"US-MPW.png"},
  "US:MPWR": {"c":"#062184"},
  "US:MRK": {"f":"US-MRK.png"},
  "US:MRNA": {"f":"US-MRNA.png"},
  "US:MRO": {"f":"US-MRO.png"},
  "US:MRVL": {"f":"US-MRVL.png"},
  "US:MS": {"f":"US-MS.png"},
  "US:MSCI": {"c":"#101e79"},
  "US:MSEX": {"f":"US-MSEX.png"},
  "US:MSFT": {"f":"US-MSFT.png"},
  "US:MSGE": {"f":"US-MSGE.png"},
  "US:MSGS": {"f":"US-MSGS.png"},
  "US:MSTR": {"f":"US-MSTR.png"},
  "US:MTB": {"f":"US-MTB.png"},
  "US:MTCH": {"f":"US-MTCH.png"},
  "US:MTD": {"f":"US-MTD.png"},
  "US:MTUM": {"f":"US-MTUM.png"},
  "US:MTZ": {"f":"US-MTZ.png"},
  "US:MU": {"f":"US-MU.png"},
  "US:MUB": {"f":"US-MUB.png"},
  "US:MUR": {"c":"#063b84"},
  "US:NARI": {"f":"US-NARI.png"},
  "US:NBIS": {"f":"US-NBIS.png"},
  "US:NBIX": {"f":"US-NBIX.png"},
  "US:NCLH": {"f":"US-NCLH.png"},
  "US:NDAQ": {"f":"US-NDAQ.png"},
  "US:NDSN": {"f":"US-NDSN.png"},
  "US:NEAR": {"f":"US-NEAR.png"},
  "US:NEE": {"f":"US-NEE.png"},
  "US:NEM": {"f":"US-NEM.png"},
  "US:NEO": {"f":"US-NEO.png"},
  "US:NEOG": {"f":"US-NEOG.png"},
  "US:NET": {"f":"US-NET.png"},
  "US:NFG": {"f":"US-NFG.png"},
  "US:NFLX": {"f":"US-NFLX.png"},
  "US:NGD": {"c":"#625528"},
  "US:NHI": {"f":"US-NHI.png"},
  "US:NI": {"f":"US-NI.png"},
  "US:NIB": {"f":"US-NIB.png"},
  "US:NINE": {"f":"US-NINE.png"},
  "US:NIO": {"f":"US-NIO.png"},
  "US:NJR": {"f":"US-NJR.png"},
  "US:NKE": {"f":"US-NKE.png"},
  "US:NLR": {"f":"US-NLR.png"},
  "US:NLY": {"c":"#283962"},
  "US:NNE": {"f":"US-NNE.png"},
  "US:NNN": {"f":"US-NNN.png"},
  "US:NNOX": {"c":"#223a67"},
  "US:NOBL": {"f":"US-NOBL.png"},
  "US:NOC": {"f":"US-NOC.png"},
  "US:NOG": {"f":"US-NOG.png"},
  "US:NOV": {"f":"US-NOV.png"},
  "US:NOW": {"f":"US-NOW.png"},
  "US:NRG": {"f":"US-NRG.png"},
  "US:NS": {"c":"#1d426d"},
  "US:NSA": {"f":"US-NSA.png"},
  "US:NSC": {"f":"US-NSC.png"},
  "US:NTAP": {"f":"US-NTAP.png"},
  "US:NTES": {"f":"US-NTES.png"},
  "US:NTLA": {"f":"US-NTLA.png"},
  "US:NTNX": {"c":"#220882"},
  "US:NTR": {"f":"US-NTR.png"},
  "US:NTRA": {"f":"US-NTRA.png"},
  "US:NTRS": {"c":"#1b6f52"},
  "US:NU": {"f":"US-NU.png"},
  "US:NUE": {"f":"US-NUE.png"},
  "US:NVCR": {"f":"US-NVCR.png"},
  "US:NVDA": {"f":"US-NVDA.png"},
  "US:NVR": {"c":"#6f1b40"},
  "US:NWE": {"f":"US-NWE.png"},
  "US:NWN": {"f":"US-NWN.png"},
  "US:NWS": {"f":"US-NWS.png"},
  "US:NWSA": {"f":"US-NWSA.png"},
  "US:NXE": {"f":"US-NXE.png"},
  "US:NXPI": {"f":"US-NXPI.png"},
  "US:NYT": {"f":"US-NYT.png"},
  "US:O": {"f":"US-O.png"},
  "US:OC": {"f":"US-OC.png"},
  "US:ODFL": {"f":"US-ODFL.png"},
  "US:OEF": {"f":"US-OEF.png"},
  "US:OGE": {"f":"US-OGE.png"},
  "US:OGS": {"f":"US-OGS.png"},
  "US:OHI": {"f":"US-OHI.png"},
  "US:OIH": {"f":"US-OIH.png"},
  "US:OII": {"f":"US-OII.png"},
  "US:OKE": {"f":"US-OKE.png"},
  "US:OKLO": {"f":"US-OKLO.png"},
  "US:OKTA": {"f":"US-OKTA.png"},
  "US:OLLI": {"f":"US-OLLI.png"},
  "US:OLN": {"f":"US-OLN.png"},
  "US:OLPX": {"f":"US-OLPX.png"},
  "US:OMC": {"f":"US-OMC.png"},
  "US:OMCL": {"f":"US-OMCL.png"},
  "US:ON": {"f":"US-ON.png"},
  "US:ONON": {"f":"US-ONON.png"},
  "US:OPCH": {"f":"US-OPCH.png"},
  "US:OPI": {"f":"US-OPI.png"},
  "US:OR": {"f":"US-OR.png"},
  "US:ORA": {"f":"US-ORA.png"},
  "US:ORCL": {"f":"US-ORCL.png"},
  "US:ORI": {"f":"US-ORI.png"},
  "US:ORLY": {"c":"#216847"},
  "US:OSCR": {"f":"US-OSCR.png"},
  "US:OTIS": {"f":"US-OTIS.png"},
  "US:OUNZ": {"f":"US-OUNZ.png"},
  "US:OVV": {"f":"US-OVV.png"},
  "US:OWL": {"f":"US-OWL.png"},
  "US:OXY": {"f":"US-OXY.png"},
  "US:PAA": {"f":"US-PAA.png"},
  "US:PAAS": {"f":"US-PAAS.png"},
  "US:PANW": {"f":"US-PANW.png"},
  "US:PARA": {"f":"US-PARA.png"},
  "US:PATH": {"f":"US-PATH.png"},
  "US:PAYC": {"f":"US-PAYC.png"},
  "US:PAYX": {"f":"US-PAYX.png"},
  "US:PBA": {"c":"#761419"},
  "US:PCAR": {"f":"US-PCAR.png"},
  "US:PCG": {"f":"US-PCG.png"},
  "US:PCTY": {"f":"US-PCTY.png"},
  "US:PCY": {"f":"US-PCY.png"},
  "US:PD": {"f":"US-PD.png"},
  "US:PDBC": {"f":"US-PDBC.png"},
  "US:PDD": {"c":"#840609"},
  "US:PEAK": {"f":"US-PEAK.png"},
  "US:PEG": {"f":"US-PEG.png"},
  "US:PEN": {"f":"US-PEN.png"},
  "US:PEP": {"f":"US-PEP.png"},
  "US:PERI": {"f":"US-PERI.png"},
  "US:PFE": {"f":"US-PFE.png"},
  "US:PFF": {"f":"US-PFF.png"},
  "US:PFFD": {"f":"US-PFFD.png"},
  "US:PFG": {"f":"US-PFG.png"},
  "US:PFGC": {"f":"US-PFGC.png"},
  "US:PFXF": {"f":"US-PFXF.png"},
  "US:PG": {"f":"US-PG.png"},
  "US:PGNY": {"c":"#731748"},
  "US:PGR": {"f":"US-PGR.png"},
  "US:PGRE": {"c":"#283662"},
  "US:PGX": {"f":"US-PGX.png"},
  "US:PH": {"f":"US-PH.png"},
  "US:PHM": {"f":"US-PHM.png"},
  "US:PHR": {"f":"US-PHR.png"},
  "US:PINE": {"f":"US-PINE.png"},
  "US:PINS": {"f":"US-PINS.png"},
  "US:PJT": {"f":"US-PJT.png"},
  "US:PLAY": {"f":"US-PLAY.png"},
  "US:PLD": {"f":"US-PLD.png"},
  "US:PLL": {"c":"#284862"},
  "US:PLTR": {"f":"US-PLTR.png"},
  "US:PLUG": {"f":"US-PLUG.png"},
  "US:PM": {"c":"#065184"},
  "US:PNC": {"f":"US-PNC.png"},
  "US:PNR": {"f":"US-PNR.png"},
  "US:PNW": {"f":"US-PNW.png"},
  "US:PODD": {"f":"US-PODD.png"},
  "US:POET": {"c":"#1e4c6c"},
  "US:POOL": {"f":"US-POOL.png"},
  "US:POR": {"c":"#284362"},
  "US:POST": {"f":"US-POST.png"},
  "US:POWI": {"f":"US-POWI.png"},
  "US:PPA": {"f":"US-PPA.png"},
  "US:PPG": {"f":"US-PPG.png"},
  "US:PPL": {"c":"#265164"},
  "US:PR": {"f":"US-PR.png"},
  "US:PRIM": {"f":"US-PRIM.png"},
  "US:PRU": {"c":"#1a4c6f"},
  "US:PRVA": {"f":"US-PRVA.png"},
  "US:PSA": {"f":"US-PSA.png"},
  "US:PSTG": {"f":"US-PSTG.png"},
  "US:PSX": {"c":"#771512"},
  "US:PTC": {"f":"US-PTC.png"},
  "US:PTEN": {"f":"US-PTEN.png"},
  "US:PVH": {"f":"US-PVH.png"},
  "US:PWR": {"f":"US-PWR.png"},
  "US:PYPL": {"f":"US-PYPL.png"},
  "US:QBTS": {"f":"US-QBTS.png"},
  "US:QCOM": {"f":"US-QCOM.png"},
  "US:QQQ": {"f":"US-QQQ.png"},
  "US:QQQM": {"f":"US-QQQM.png"},
  "US:QRVO": {"f":"US-QRVO.png"},
  "US:QSR": {"f":"US-QSR.png"},
  "US:QUAL": {"f":"US-QUAL.png"},
  "US:RACE": {"f":"US-RACE.png"},
  "US:RARE": {"f":"US-RARE.png"},
  "US:RBLX": {"f":"US-RBLX.png"},
  "US:RBRK": {"f":"US-RBRK.png"},
  "US:RCL": {"f":"US-RCL.png"},
  "US:RDDT": {"f":"US-RDDT.png"},
  "US:RDW": {"f":"US-RDW.png"},
  "US:REAL": {"f":"US-REAL.png"},
  "US:REG": {"f":"US-REG.png"},
  "US:REGN": {"f":"US-REGN.png"},
  "US:REMX": {"f":"US-REMX.png"},
  "US:RES": {"f":"US-RES.png"},
  "US:REXR": {"f":"US-REXR.png"},
  "US:RF": {"f":"US-RF.png"},
  "US:RGLD": {"f":"US-RGLD.png"},
  "US:RGTI": {"f":"US-RGTI.png"},
  "US:RIO": {"f":"US-RIO.png"},
  "US:RIOT": {"f":"US-RIOT.png"},
  "US:RIVN": {"f":"US-RIVN.png"},
  "US:RJF": {"c":"#284262"},
  "US:RKLB": {"f":"US-RKLB.png"},
  "US:RLI": {"f":"US-RLI.png"},
  "US:RMBS": {"f":"US-RMBS.png"},
  "US:RMD": {"f":"US-RMD.png"},
  "US:RNG": {"f":"US-RNG.png"},
  "US:RNR": {"f":"US-RNR.png"},
  "US:ROAD": {"f":"US-ROAD.png"},
  "US:ROK": {"f":"US-ROK.png"},
  "US:ROKU": {"f":"US-ROKU.png"},
  "US:ROOT": {"f":"US-ROOT.png"},
  "US:ROP": {"f":"US-ROP.png"},
  "US:ROST": {"f":"US-ROST.png"},
  "US:RPM": {"c":"#1e3b6b"},
  "US:RRC": {"f":"US-RRC.png"},
  "US:RS": {"c":"#284b62"},
  "US:RSG": {"f":"US-RSG.png"},
  "US:RSP": {"c":"#282f62"},
  "US:RTX": {"f":"US-RTX.png"},
  "US:RVTY": {"f":"US-RVTY.png"},
  "US:RXO": {"f":"US-RXO.png"},
  "US:RXRX": {"f":"US-RXRX.png"},
  "US:S": {"f":"US-S.png"},
  "US:SAIA": {"f":"US-SAIA.png"},
  "US:SAIC": {"f":"US-SAIC.png"},
  "US:SAND": {"f":"US-SAND.png"},
  "US:SATO": {"f":"US-SATO.png"},
  "US:SBAC": {"f":"US-SBAC.png"},
  "US:SBRA": {"f":"US-SBRA.png"},
  "US:SBSW": {"c":"#625328"},
  "US:SBUX": {"c":"#098151"},
  "US:SCCO": {"f":"US-SCCO.png"},
  "US:SCHA": {"f":"US-SCHA.png"},
  "US:SCHB": {"f":"US-SCHB.png"},
  "US:SCHC": {"f":"US-SCHC.png"},
  "US:SCHD": {"f":"US-SCHD.png"},
  "US:SCHE": {"f":"US-SCHE.png"},
  "US:SCHF": {"f":"US-SCHF.png"},
  "US:SCHG": {"f":"US-SCHG.png"},
  "US:SCHH": {"f":"US-SCHH.png"},
  "US:SCHM": {"f":"US-SCHM.png"},
  "US:SCHO": {"f":"US-SCHO.png"},
  "US:SCHP": {"f":"US-SCHP.png"},
  "US:SCHQ": {"f":"US-SCHQ.png"},
  "US:SCHR": {"f":"US-SCHR.png"},
  "US:SCHW": {"f":"US-SCHW.png"},
  "US:SCHX": {"f":"US-SCHX.png"},
  "US:SCO": {"f":"US-SCO.png"},
  "US:SDY": {"f":"US-SDY.png"},
  "US:SE": {"f":"US-SE.png"},
  "US:SEAS": {"c":"#265364"},
  "US:SEDG": {"c":"#761417"},
  "US:SENS": {"f":"US-SENS.png"},
  "US:SF": {"c":"#284762"},
  "US:SGML": {"f":"US-SGML.png"},
  "US:SGOV": {"f":"US-SGOV.png"},
  "US:SHAK": {"f":"US-SHAK.png"},
  "US:SHOP": {"f":"US-SHOP.png"},
  "US:SHV": {"f":"US-SHV.png"},
  "US:SHW": {"f":"US-SHW.png"},
  "US:SHY": {"f":"US-SHY.png"},
  "US:SID": {"f":"US-SID.png"},
  "US:SIL": {"f":"US-SIL.png"},
  "US:SILJ": {"f":"US-SILJ.png"},
  "US:SITM": {"f":"US-SITM.png"},
  "US:SIX": {"f":"US-SIX.png"},
  "US:SJM": {"f":"US-SJM.png"},
  "US:SJNK": {"f":"US-SJNK.png"},
  "US:SJW": {"c":"#282c62"},
  "US:SKX": {"f":"US-SKX.png"},
  "US:SKYY": {"f":"US-SKYY.png"},
  "US:SLAB": {"c":"#76141a"},
  "US:SLB": {"f":"US-SLB.png"},
  "US:SLV": {"f":"US-SLV.png"},
  "US:SLX": {"f":"US-SLX.png"},
  "US:SM": {"f":"US-SM.png"},
  "US:SMCI": {"f":"US-SMCI.png"},
  "US:SMG": {"f":"US-SMG.png"},
  "US:SMH": {"f":"US-SMH.png"},
  "US:SMMV": {"f":"US-SMMV.png"},
  "US:SMPL": {"f":"US-SMPL.png"},
  "US:SMR": {"f":"US-SMR.png"},
  "US:SN": {"f":"US-SN.png"},
  "US:SNAP": {"f":"US-SNAP.png"},
  "US:SNOW": {"f":"US-SNOW.png"},
  "US:SNPS": {"f":"US-SNPS.png"},
  "US:SO": {"f":"US-SO.png"},
  "US:SOUN": {"f":"US-SOUN.png"},
  "US:SOXX": {"f":"US-SOXX.png"},
  "US:SOYB": {"f":"US-SOYB.png"},
  "US:SPBO": {"f":"US-SPBO.png"},
  "US:SPG": {"f":"US-SPG.png"},
  "US:SPGI": {"f":"US-SPGI.png"},
  "US:SPHY": {"f":"US-SPHY.png"},
  "US:SPIB": {"f":"US-SPIB.png"},
  "US:SPLG": {"f":"US-SPLG.png"},
  "US:SPLV": {"f":"US-SPLV.png"},
  "US:SPMD": {"f":"US-SPMD.png"},
  "US:SPMO": {"f":"US-SPMO.png"},
  "US:SPOT": {"f":"US-SPOT.png"},
  "US:SPR": {"f":"US-SPR.png"},
  "US:SPSB": {"f":"US-SPSB.png"},
  "US:SPSM": {"f":"US-SPSM.png"},
  "US:SPTI": {"f":"US-SPTI.png"},
  "US:SPTL": {"f":"US-SPTL.png"},
  "US:SPTS": {"f":"US-SPTS.png"},
  "US:SPY": {"f":"US-SPY.png"},
  "US:SPYG": {"c":"#3e6228"},
  "US:SPYV": {"c":"#3e6228"},
  "US:SQM": {"f":"US-SQM.png"},
  "US:SR": {"f":"US-SR.png"},
  "US:SRC": {"c":"#283862"},
  "US:SRE": {"f":"US-SRE.png"},
  "US:SRLN": {"f":"US-SRLN.png"},
  "US:SRPT": {"f":"US-SRPT.png"},
  "US:SSRM": {"f":"US-SSRM.png"},
  "US:STAG": {"f":"US-STAG.png"},
  "US:STE": {"c":"#154575"},
  "US:STIP": {"f":"US-STIP.png"},
  "US:STLA": {"f":"US-STLA.png"},
  "US:STLD": {"f":"US-STLD.png"},
  "US:STM": {"f":"US-STM.png"},
  "US:STRL": {"f":"US-STRL.png"},
  "US:STT": {"f":"US-STT.png"},
  "US:STWD": {"f":"US-STWD.png"},
  "US:STX": {"f":"US-STX.png"},
  "US:STZ": {"f":"US-STZ.png"},
  "US:SUI": {"c":"#843906"},
  "US:SUM": {"c":"#283e62"},
  "US:SUMO": {"f":"US-SUMO.png"},
  "US:SUN": {"f":"US-SUN.png"},
  "US:SUSC": {"f":"US-SUSC.png"},
  "US:SWAV": {"c":"#265763"},
  "US:SWK": {"f":"US-SWK.png"},
  "US:SWKS": {"f":"US-SWKS.png"},
  "US:SWX": {"f":"US-SWX.png"},
  "US:SXT": {"c":"#7f630b"},
  "US:SYF": {"f":"US-SYF.png"},
  "US:SYY": {"f":"US-SYY.png"},
  "US:T": {"f":"US-T.png"},
  "US:TAP": {"f":"US-TAP.png"},
  "US:TCEHY": {"f":"US-TCEHY.png"},
  "US:TDG": {"c":"#284b62"},
  "US:TDY": {"f":"US-TDY.png"},
  "US:TEAM": {"f":"US-TEAM.png"},
  "US:TECH": {"f":"US-TECH.png"},
  "US:TECK": {"f":"US-TECK.png"},
  "US:TEM": {"f":"US-TEM.png"},
  "US:TENB": {"c":"#0b3d7e"},
  "US:TER": {"f":"US-TER.png"},
  "US:TFC": {"f":"US-TFC.png"},
  "US:TGT": {"f":"US-TGT.png"},
  "US:TGTX": {"f":"US-TGTX.png"},
  "US:THC": {"f":"US-THC.png"},
  "US:THS": {"f":"US-THS.png"},
  "US:TIP": {"f":"US-TIP.png"},
  "US:TJX": {"f":"US-TJX.png"},
  "US:TLH": {"f":"US-TLH.png"},
  "US:TLN": {"f":"US-TLN.png"},
  "US:TLT": {"f":"US-TLT.png"},
  "US:TM": {"f":"US-TM.png"},
  "US:TMC": {"f":"US-TMC.png"},
  "US:TMO": {"f":"US-TMO.png"},
  "US:TMUS": {"f":"US-TMUS.png"},
  "US:TNDM": {"f":"US-TNDM.png"},
  "US:TOL": {"f":"US-TOL.png"},
  "US:TOST": {"f":"US-TOST.png"},
  "US:TPR": {"f":"US-TPR.png"},
  "US:TREE": {"f":"US-TREE.png"},
  "US:TREX": {"f":"US-TREX.png"},
  "US:TRGP": {"f":"US-TRGP.png"},
  "US:TRN": {"f":"US-TRN.png"},
  "US:TRNO": {"f":"US-TRNO.png"},
  "US:TROW": {"f":"US-TROW.png"},
  "US:TROX": {"c":"#112479"},
  "US:TRP": {"f":"US-TRP.png"},
  "US:TRV": {"f":"US-TRV.png"},
  "US:TSCO": {"f":"US-TSCO.png"},
  "US:TSLA": {"f":"US-TSLA.png"},
  "US:TSM": {"f":"US-TSM.png"},
  "US:TSN": {"f":"US-TSN.png"},
  "US:TT": {"f":"US-TT.png"},
  "US:TTD": {"f":"US-TTD.png"},
  "US:TTEK": {"c":"#144c76"},
  "US:TTWO": {"f":"US-TTWO.png"},
  "US:TW": {"f":"US-TW.png"},
  "US:TWLO": {"f":"US-TWLO.png"},
  "US:TXN": {"f":"US-TXN.png"},
  "US:TXRH": {"f":"US-TXRH.png"},
  "US:TXT": {"f":"US-TXT.png"},
  "US:TYL": {"f":"US-TYL.png"},
  "US:U": {"f":"US-U.png"},
  "US:UA": {"f":"US-UA.png"},
  "US:UAA": {"f":"US-UAA.png"},
  "US:UAL": {"c":"#0e0e7c"},
  "US:UBER": {"f":"US-UBER.png"},
  "US:UCO": {"f":"US-UCO.png"},
  "US:UDR": {"f":"US-UDR.png"},
  "US:UEC": {"f":"US-UEC.png"},
  "US:UHS": {"c":"#63272e"},
  "US:ULTA": {"f":"US-ULTA.png"},
  "US:UMC": {"f":"US-UMC.png"},
  "US:UNH": {"f":"US-UNH.png"},
  "US:UNP": {"f":"US-UNP.png"},
  "US:UPS": {"f":"US-UPS.png"},
  "US:UPST": {"f":"US-UPST.png"},
  "US:URA": {"f":"US-URA.png"},
  "US:URBN": {"f":"US-URBN.png"},
  "US:URI": {"f":"US-URI.png"},
  "US:URNM": {"f":"US-URNM.png"},
  "US:URTH": {"f":"US-URTH.png"},
  "US:USB": {"f":"US-USB.png"},
  "US:USFD": {"f":"US-USFD.png"},
  "US:USHY": {"f":"US-USHY.png"},
  "US:USIG": {"f":"US-USIG.png"},
  "US:USL": {"f":"US-USL.png"},
  "US:USLM": {"f":"US-USLM.png"},
  "US:USMV": {"f":"US-USMV.png"},
  "US:USO": {"f":"US-USO.png"},
  "US:UTL": {"f":"US-UTL.png"},
  "US:UTZ": {"f":"US-UTZ.png"},
  "US:UUUU": {"f":"US-UUUU.png"},
  "US:V": {"f":"US-V.png"},
  "US:VALE": {"f":"US-VALE.png"},
  "US:VAW": {"f":"US-VAW.png"},
  "US:VB": {"f":"US-VB.png"},
  "US:VBK": {"f":"US-VBK.png"},
  "US:VBR": {"f":"US-VBR.png"},
  "US:VCIT": {"f":"US-VCIT.png"},
  "US:VCR": {"f":"US-VCR.png"},
  "US:VCSH": {"f":"US-VCSH.png"},
  "US:VDC": {"f":"US-VDC.png"},
  "US:VDE": {"f":"US-VDE.png"},
  "US:VEA": {"f":"US-VEA.png"},
  "US:VEU": {"f":"US-VEU.png"},
  "US:VFC": {"f":"US-VFC.png"},
  "US:VFH": {"f":"US-VFH.png"},
  "US:VGIT": {"f":"US-VGIT.png"},
  "US:VGK": {"f":"US-VGK.png"},
  "US:VGLT": {"f":"US-VGLT.png"},
  "US:VGSH": {"f":"US-VGSH.png"},
  "US:VGT": {"f":"US-VGT.png"},
  "US:VHT": {"f":"US-VHT.png"},
  "US:VICI": {"f":"US-VICI.png"},
  "US:VIG": {"f":"US-VIG.png"},
  "US:VIRT": {"f":"US-VIRT.png"},
  "US:VIS": {"f":"US-VIS.png"},
  "US:VITL": {"c":"#761914"},
  "US:VKTX": {"c":"#652b25"},
  "US:VLO": {"f":"US-VLO.png"},
  "US:VMC": {"c":"#252c65"},
  "US:VMI": {"f":"US-VMI.png"},
  "US:VNO": {"c":"#284262"},
  "US:VNOM": {"f":"US-VNOM.png"},
  "US:VNQ": {"f":"US-VNQ.png"},
  "US:VO": {"f":"US-VO.png"},
  "US:VOE": {"f":"US-VOE.png"},
  "US:VONE": {"f":"US-VONE.png"},
  "US:VONG": {"f":"US-VONG.png"},
  "US:VONV": {"f":"US-VONV.png"},
  "US:VOO": {"f":"US-VOO.png"},
  "US:VOT": {"f":"US-VOT.png"},
  "US:VOX": {"f":"US-VOX.png"},
  "US:VOYA": {"c":"#804a09"},
  "US:VPL": {"f":"US-VPL.png"},
  "US:VPU": {"f":"US-VPU.png"},
  "US:VRP": {"f":"US-VRP.png"},
  "US:VRSK": {"f":"US-VRSK.png"},
  "US:VRSN": {"f":"US-VRSN.png"},
  "US:VRT": {"f":"US-VRT.png"},
  "US:VRTX": {"f":"US-VRTX.png"},
  "US:VSCO": {"f":"US-VSCO.png"},
  "US:VST": {"f":"US-VST.png"},
  "US:VT": {"f":"US-VT.png"},
  "US:VTEB": {"f":"US-VTEB.png"},
  "US:VTHR": {"f":"US-VTHR.png"},
  "US:VTI": {"f":"US-VTI.png"},
  "US:VTIP": {"f":"US-VTIP.png"},
  "US:VTR": {"f":"US-VTR.png"},
  "US:VTRS": {"c":"#826d07"},
  "US:VTV": {"f":"US-VTV.png"},
  "US:VTWO": {"f":"US-VTWO.png"},
  "US:VUG": {"f":"US-VUG.png"},
  "US:VUZI": {"f":"US-VUZI.png"},
  "US:VWO": {"f":"US-VWO.png"},
  "US:VWOB": {"f":"US-VWOB.png"},
  "US:VXUS": {"f":"US-VXUS.png"},
  "US:VYM": {"f":"US-VYM.png"},
  "US:VZ": {"f":"US-VZ.png"},
  "US:W": {"f":"US-W.png"},
  "US:WAB": {"f":"US-WAB.png"},
  "US:WAT": {"f":"US-WAT.png"},
  "US:WBA": {"f":"US-WBA.png"},
  "US:WBD": {"f":"US-WBD.png"},
  "US:WBS": {"f":"US-WBS.png"},
  "US:WCLD": {"f":"US-WCLD.png"},
  "US:WCN": {"c":"#1a7053"},
  "US:WD": {"f":"US-WD.png"},
  "US:WDAY": {"f":"US-WDAY.png"},
  "US:WDC": {"f":"US-WDC.png"},
  "US:WEAT": {"c":"#467119"},
  "US:WEC": {"f":"US-WEC.png"},
  "US:WELL": {"f":"US-WELL.png"},
  "US:WEN": {"f":"US-WEN.png"},
  "US:WERN": {"f":"US-WERN.png"},
  "US:WES": {"c":"#284762"},
  "US:WFC": {"f":"US-WFC.png"},
  "US:WFRD": {"f":"US-WFRD.png"},
  "US:WGMI": {"f":"US-WGMI.png"},
  "US:WING": {"f":"US-WING.png"},
  "US:WIP": {"f":"US-WIP.png"},
  "US:WIT": {"c":"#761343"},
  "US:WK": {"c":"#457217"},
  "US:WLK": {"f":"US-WLK.png"},
  "US:WM": {"f":"US-WM.png"},
  "US:WMB": {"f":"US-WMB.png"},
  "US:WMG": {"f":"US-WMG.png"},
  "US:WMS": {"f":"US-WMS.png"},
  "US:WMT": {"f":"US-WMT.png"},
  "US:WOLF": {"f":"US-WOLF.png"},
  "US:WOOD": {"f":"US-WOOD.png"},
  "US:WOR": {"f":"US-WOR.png"},
  "US:WPC": {"f":"US-WPC.png"},
  "US:WPM": {"f":"US-WPM.png"},
  "US:WRB": {"f":"US-WRB.png"},
  "US:WRBY": {"f":"US-WRBY.png"},
  "US:WST": {"f":"US-WST.png"},
  "US:WTS": {"c":"#1a4f6f"},
  "US:WTW": {"f":"US-WTW.png"},
  "US:WULF": {"f":"US-WULF.png"},
  "US:WWD": {"c":"#642726"},
  "US:WY": {"f":"US-WY.png"},
  "US:WYNN": {"f":"US-WYNN.png"},
  "US:X": {"f":"US-X.png"},
  "US:XAR": {"f":"US-XAR.png"},
  "US:XBI": {"f":"US-XBI.png"},
  "US:XEL": {"f":"US-XEL.png"},
  "US:XLB": {"f":"US-SPY.png"},
  "US:XLC": {"f":"US-SPY.png"},
  "US:XLE": {"c":"#84061e"},
  "US:XLF": {"c":"#84061e"},
  "US:XLG": {"f":"US-XLG.png"},
  "US:XLI": {"f":"US-SPY.png"},
  "US:XLK": {"f":"US-SPY.png"},
  "US:XLP": {"f":"US-SPY.png"},
  "US:XLRE": {"f":"US-SPY.png"},
  "US:XLU": {"f":"US-SPY.png"},
  "US:XLV": {"f":"US-SPY.png"},
  "US:XLY": {"f":"US-SPY.png"},
  "US:XOM": {"f":"US-XOM.png"},
  "US:XOP": {"f":"US-XOP.png"},
  "US:XPEV": {"f":"US-XPEV.png"},
  "US:XPO": {"f":"US-XPO.png"},
  "US:XRT": {"f":"US-XRT.png"},
  "US:XYL": {"f":"US-XYL.png"},
  "US:XYZ": {"f":"US-XYZ.png"},
  "US:YETI": {"f":"US-YETI.png"},
  "US:YORW": {"c":"#206a50"},
  "US:YUM": {"f":"US-YUM.png"},
  "US:Z": {"f":"US-Z.png"},
  "US:ZBH": {"c":"#0a5580"},
  "US:ZBRA": {"f":"US-ZBRA.png"},
  "US:ZG": {"f":"US-ZG.png"},
  "US:ZM": {"f":"US-ZM.png"},
  "US:ZS": {"f":"US-ZS.png"},
  "US:ZTO": {"f":"US-ZTO.png"},
  "US:ZTS": {"f":"US-ZTS.png"},
};
// <<< LOGO_MANIFEST_END

// Market-scoped so `SOL` cannot resolve Sasol art for Solana (see the logo spec).
function logoFor(ticker, market) {
  if (!ticker || !market) return null;
  return LOGO_MANIFEST[market + ':' + ticker] || null;
}

return { RIBBON_CATALOG, RIBBON_CATALOG_MAP, INDICATOR_INFO, BUILTIN_MACRO_2026, RULES, SECTOR_ETF, SECTOR_TREND_WINDOWS, SECTOR_FWD_PE, MARKETS, DISPLAY_CURRENCIES, CURRENCY_SYMBOLS, ROTATION_COPY, ROTATION_SECTOR_SHORT, LOGO_MANIFEST, logoFor };
});
